// Evolution data: Aula 3 -> Aula 4 (GUT revisado + novos riscos R024-R031)
import { Risk } from './models';

export const RISKS_AULA3: Risk[] = [
  {
    id: 'R003',
    fonteDeRisco: 'FE - Fornecedores',
    descricaoFonte: 'Dependência de infraestrutura de fornecedor',
    ameaca: 'Interrupção do serviço pelo fornecedor',
    descricaoRisco: 'Indisponibilidade do SAP-FI entre os dias 25 a 30 de cada mês ocasionando parada no faturamento',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 2,
    impacto: 5,
    riscoInerente: 10,
    consequencia: '- Paralisação do faturamento\n- Atraso no fluzo de caixa\n- Risco de multas e/ou penalidades\n- Acumulo de operações e retrabalho\n- Impacto no EBITDA\n- Aumento de reclamação de clientes',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar - implementar Plano de Continuidade de Negócios com definição de RTO e RPO, incluindo procedimentos de contingência manual; realização de testes periodicos\nTransferir - acordo de co-responsabilidde com fornecedor',
    controles: 'Seguro cibernetico\nBackup',
    responsavel: '',
    prazo: '',
    kri: '',
    acaoKri: '',
    quemMede: '',
    quandoMede: '',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R004',
    fonteDeRisco: 'FI - Seguranca, saude e meio ambiente',
    descricaoFonte: 'Segurança física dos CDs insuficientes no período noturno',
    ameaca: 'Assaltantes podem invadir o local, subtrair produtos, atingir colaboradores, paralisar a operação e impactar a imagem da instituição',
    descricaoRisco: 'Um assalto pode impactar a continuidade dos negócios e gerar prejuízos financeiros e operacionais.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Operacional',
    probabilidade: 3,
    impacto: 4,
    riscoInerente: 12,
    consequencia: '- Perda de produtos\n- Atrasos na operação\n- Afastamento de funcionarios\n- Impacto na imagem da organização\n- Maior probabilidade de novas ocorrencias',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Transferência e Mitigação',
    controles: 'Contratação de seguro patrimonial / Contratação de Segurança Externa para apoio em incidentes / Aumento do efetivo da segurança interna no período noturno / Ativação de sistema de CFVT no período noturno',
    responsavel: 'Diretor de Segurança',
    prazo: '3 meses',
    kri: 'KRI 1 - Número de tentativas de assaltos bem-sucedidas por mês = 2\nKRI 2 - Quantidade de horas de paralisação de produção por tentativas de assaltos por mês = 4h',
    acaoKri: 'Reavaliação das estruturas de segurança\nEntrevista com os envolvidos nos incidentes para coleta de dados para aperfeiçoamento das brechas',
    quemMede: 'Área de Riscos',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: 'Analise de eficacia dos sistemas e processos de segurança implementados',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R005',
    fonteDeRisco: 'FE - Cibersegurança ou Tecnologicas externas',
    descricaoFonte: 'Falta de governança de TI e inexistência de uma estrutura formal de defesa cibernética.',
    ameaca: 'Exploração de vulnerabilidades por agentes externos (hackers), vazamento de dados por funcionários e indisponibilidade de sistemas críticos por falta de monitoramento',
    descricaoRisco: 'Incerteza quanto à capacidade da empresa em proteger seus dados e manter a operação online devido à inexistência de um responsável técnico (CISO/Gestor de SI) para gerenciar as defesas',
    estrategico: 'SIM',
    tipoRisco: 'Risco Operacional',
    probabilidade: 4,
    impacto: 5,
    riscoInerente: 20,
    consequencia: 'Perda de receita por queda do site, multas regulatórias, perda de reputação e impedimento de processos de fusão/venda (M&A)',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Evitar',
    controles: 'Contratação imediata de um CISO ou consultoria especializada em GRC; implementação de Política de Segurança da Informação e segregação de funções entre Infraestrutura e Segurança',
    responsavel: 'Especialista em Segurança Digital e Riscos Cyber',
    prazo: '30 a 60 dias para contratação e diagnóstico inicial',
    kri: 'Tentativa de acesso não autorizado em repositórios de código ou falhas no SAP-FI por mais de 4 horas',
    acaoKri: 'Acionamento do Plano de Resposta a Incidentes (a ser criado) e isolamento de sistemas afetados',
    quemMede: 'Especialista em Segurança Digital',
    quandoMede: 'Tempo real (Monitoramento contínuo)',
    reducaoPretendida: 4,
    riscoResidual: 3,
    eficaciaTratamento: 'Através de Auditorias de TI e redução no número de incidentes de vazamento reportados nos próximos 6 meses',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R006',
    fonteDeRisco: 'FE - Clientes',
    descricaoFonte: 'Comportamento imprevisível dos clientes, aumento de reclamações por erros de preços, atrasos e falhas nas entregas',
    ameaca: 'Ação dos clientes insatisfeitos explorando falhas de entrega, erros de preços e inconsistências operacionais, resultando em reclamações públicas, cancelamentos e perda de confiança na marca.',
    descricaoRisco: 'A insatisfação dos clientes ocasionando queda nas vendas, aumento de cancelamentos e devoluções, piora na reputação e redução da fidelização, comprometendo os objetivos de crescimento de mercado, eficiência operacional e rentabilidade definidos pela empresa.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: 'Danos à reputação, perda de vendas, cancelamentos e devoluções, comprometendo objetivos de mercado e fidelização.',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Padronização e dupla aprovação no cadastro de preços; melhoria dos SLAs com parceiros logísticos; monitoramento contínuo de reclamações, cancelamentos e devoluções; auditorias de preços e promoções; ajustes rápidos em erros identificados; acionamento de contingência logística; revisão de indicadores de satisfação e governança periódica com áreas responsáveis e parceiros.',
    responsavel: 'Diretoria Comercial / Experiência do Cliente (Owner). Corresponsáveis: Operações/Logística (SLA e OTIF), SAC (reclamações/NPS) e TI/Comercial (governança de preços e publicações).',
    prazo: '4 meses',
    kri: 'Aumento de reclamações acima da média histórica, taxa de cancelamentos superior a 5% e devoluções acima de 10% no mês.',
    acaoKri: 'Acionar plano de resposta ao cliente, corrigir imediatamente erros de preço ou falhas de entrega, comunicar clientes afetados, revisar SLAs com parceiros e priorizar casos críticos no SAC para reduzir impacto e recuperar confiança.',
    quemMede: 'SAC / Atendimento ao Cliente, com apoio das áreas Comercial e Operações (Logística).',
    quandoMede: 'Mensalmente, com acompanhamento semanal dos indicadores críticos de reclamações, cancelamentos e devoluções.',
    reducaoPretendida: 1,
    riscoResidual: 6,
    eficaciaTratamento: 'Por meio da redução consistente das reclamações dos clientes, diminuição das taxas de cancelamentos e devoluções, melhoria no cumprimento dos prazos de entrega (OTIF) e redução de erros de preços, verificados por meio de indicadores mensais comparados à linha de base anterior aos controles.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R007',
    fonteDeRisco: 'FE - Cibersegurança ou Tecnologicas externas',
    descricaoFonte: 'Inexistência do PCN para a infraestrutura da XYZ Cloud',
    ameaca: 'Indisponibilidade do ambiente de produção da XYZ Cloud',
    descricaoRisco: 'Falha no hardware dos servidores do DataCenter da XYZ Cloud, que osaciona a indisponibilidade do ambiente produtivo da DAMACORP.',
    estrategico: 'NÃO',
    tipoRisco: 'Risco Tecnológico',
    probabilidade: 4,
    impacto: 5,
    riscoInerente: 20,
    consequencia: '- Perca de Clientes\n- Perca de Dados',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Contratação imediata de uma consultoria especializada em Continuidade de Negócios, que possui como base a norma ISO22301, para a estruturação do SGCN, elaborando a Análise de Impacto de Negócio (BIA), Análise de Risco, Definição das Estratégias de Contingência (Tecnologia e Negócio) e elaboração dos testes das contingências mapeadas.',
    responsavel: 'Gestão de Tecnologia e Negócio',
    prazo: '150 a 180 dias para contratação e estruturação do SGCN',
    kri: 'KRI1 → Instabilidade do ambiente produtivo\nKRI2 → Alta latência do ambiente produtivo\nKRI3 → Indisponibilidade do ambiente produtivo',
    acaoKri: 'Acionamento do Plano de Continuidade de Negócios para recuperação da infraestrutura',
    quemMede: 'Equipe de Monitoramento;\nEquipe de Negócios;\nEquipe de Tecnologia;\nEquipe de Resposta a Incidentes.',
    quandoMede: 'Tempo real (Monitoramento contínuo)',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R008',
    fonteDeRisco: 'FE - Meio ambiente',
    descricaoFonte: 'Eventos climáticos severos ocasionando atrasos e interrupções na logística, aumentando reclamações, cancelamentos e impactando vendas e reputação.',
    ameaca: 'Interdições de vias, enchentes, tempestades e alagamentos explorando a dependência logística e a vulnerabilidade dos CDs e das rotas de transporte, causando interrupções e atrasos generalizados nas entregas.',
    descricaoRisco: 'Incerteza sobre cumprir metas de satisfação, vendas e reputação devido a atrasos e interrupções logísticas causadas por eventos climáticos severos.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 3,
    impacto: 4,
    riscoInerente: 12,
    consequencia: 'Atrasos nas entregas, aumento de reclamações, cancelamentos e prejuízos, com impacto direto na reputação e nas vendas.',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Plano de contingência climática com rotas alternativas e operadores adicionais; monitoramento meteorológico; acionamento imediato de transportadoras alternativas; comunicação proativa aos clientes; revisão de SLAs logísticos; análise de desempenho em clima severo e lições aprendidas.',
    responsavel: 'Diretoria de Operações (Logística',
    prazo: '3 meses para implantação do plano de contingência e ajustes de SLAs, com monitoramento semanal em períodos de chuva intensa.',
    kri: 'OTIF < 90%, aumento de reclamações por atraso e cancelamentos acima de 5% durante eventos climáticos.',
    acaoKri: 'Acionar contingência logística, priorizar entregas críticas, comunicar clientes afetados e revisar SLAs com transportadoras para restabelecer o nível de serviço.',
    quemMede: 'Operações / Logística (Owner da medição de OTIF e desempenho de transportadoras), com apoio do SAC/Atendimento (reclamações por atraso) e Comercial (promessas de prazo).',
    quandoMede: 'Mensalmente, com acompanhamento semanal dos indicadores críticos (OTIF por rota/região, reclamações por atraso e cancelamentos) durante períodos de chuva intensa.',
    reducaoPretendida: 3,
    riscoResidual: 4,
    eficaciaTratamento: 'Melhora do OTIF, redução de atrasos por clima, queda nas reclamações por entrega, diminuição de cancelamentos e devoluções, comparados à linha de base anterior.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R009',
    fonteDeRisco: 'FI - Diretoria / Liderança / Sócios',
    descricaoFonte: 'Conexão familiar de sócio com entidade envolvida em esquemas de corrupção e lavagem de dinheiro',
    ameaca: 'Investigações da Polícia Federal (Operações derivadas), bloqueio de contas judiciais, busca e apreensão nos CDs ou sede e desconfiança de investidores',
    descricaoRisco: 'Incerteza quanto à continuidade do negócio e manutenção da imagem institucional devido ao receio de "contágio" reputacional ou envolvimento indireto em processos de corrupção',
    estrategico: 'SIM',
    tipoRisco: 'Risco Reputacional',
    probabilidade: 3,
    impacto: 5,
    riscoInerente: 15,
    consequencia: 'Rescisão de contratos com fabricantes, recusa de crédito bancário, cancelamento de parcerias logísticas e impossibilidade de venda da empresa (M&A)',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Aceitar',
    controles: 'Implementação de um Programa de Compliance robusto; Canal de Denúncias externo; Auditoria independente (Big Four) para validar balanços; Cláusulas de Due Diligence rigorosas em novos contratos',
    responsavel: 'Direção Estratégica e Relações de Mercado',
    prazo: '90 dias para implementação do programa de integridade',
    kri: 'Citação do nome da DAMACORP ou de seus sócios em depoimentos, mídias ou investigações correlatas',
    acaoKri: 'Acionamento do Gabinete de Crise (Assessoria de Imprensa e Jurídico Criminalista) e afastamento preventivo do sócio de funções executivas',
    quemMede: 'Direção Estratégica',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 3,
    riscoResidual: 4,
    eficaciaTratamento: 'Através de notas de auditoria sem ressalvas e manutenção das linhas de crédito bancário operacionais',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R010',
    fonteDeRisco: 'FE - Cibersegurança ou Tecnologicas externas',
    descricaoFonte: 'Ataque, invasão, DOS',
    ameaca: 'Facilitação por meio de envolvimento de funcionarios',
    descricaoRisco: 'Ataque ou invasão ocasionando alteração de preços de produtos caros',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 5,
    impacto: 5,
    riscoInerente: 25,
    consequencia: '- Perda financeira imediata\n - Aumento de cancelamento e reembolso\n- Interrupção de vendas para correção dos preços\n- Danos à reputação e imagem',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar\n- Implementação de controles rigorosos de acesso\n- Monitoramento contínuo\n- Desenvolvimento seguro (proibir BYOD; repositorios internos seguros; revisão de código)',
    controles: '',
    responsavel: '',
    prazo: '',
    kri: '',
    acaoKri: '',
    quemMede: '',
    quandoMede: '',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R011',
    fonteDeRisco: 'FE - Fornecedores',
    descricaoFonte: 'Ausência do processo de KYS dentro da DAMACORP',
    ameaca: 'Fraudes internas, corrupção, desvio de verba.',
    descricaoRisco: 'Contratação de fornecedores fraudulentos que podem gerar fraudes na companhia.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Operacional',
    probabilidade: 5,
    impacto: 3,
    riscoInerente: 15,
    consequencia: '- Perca de Cliente;\n- Lavagem de dinheiro;\n- Multas;\n- Perda de marketshare;\n- Imagem afetada.',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar:\n- Implementar uma esteira de Homologação de Serviço de Terceiros na companhia;\n- Elaboração das áreas pareceristas;\n- Elaboração da esteira de fornecedores relevantes para a companhia;\n- Elaboração da gestão orçamentária para contratação de terceiros.',
    controles: 'Elaboração do processo de Homologação de Prestadores de Serviço, para definir os riscos que o prestador de serviço pode trazer para a companhia e definir quais prestadores não são recomendados a contratação.',
    responsavel: '- Governança de Terceiros;\n- Compliance;\n- Segurança da Informação;\n- Continuidade de Negócios;\n- Arquitetura de Tecnologia',
    prazo: '30 dias',
    kri: 'KRI1 → Fornecedor possui um risco alto ou acima conforme norma;\nKRI2 → Fornecedor possui histórico de indícios de trabalho infantil;\nKRI3 → Fornecedor não cumpre o mínimo da régua de risco estabelecida por cada área parecerista.',
    acaoKri: 'Plano de ação para o prestador de serviço se adequar as necessidades da companhia',
    quemMede: 'Áreas pareceristas',
    quandoMede: 'A cada avaliação',
    reducaoPretendida: 3,
    riscoResidual: 1,
    eficaciaTratamento: 'A conformidade dos prestadores de serviço conforme régua de risco.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R012',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Aumento da diversificação de produtos',
    ameaca: 'Aumento significativo da atuação das áreas de pesquisa, mkt e produção em mercados desconhecidos',
    descricaoRisco: 'A empresa pretende atuar em ramos diversificados, os quais não possui experiencia, dificultando o ganho de marketshare e adequação dos processos internos',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 3,
    impacto: 3,
    riscoInerente: 9,
    consequencia: '- Perda de clientes\n- Diminuição de faturamento\n- Aumento de custos de estoque',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Transferir',
    controles: '- Contratação de marketing externo de nicho específico dos novos produtos\n- Divisão do CD por tipo de produto',
    responsavel: 'Diretorias Comerciais e de Logistica',
    prazo: '3 meses',
    kri: '- Não atingimento dos objetivos de vendas durante 3 meses consecutivos\n- Aumento de 10% de perdas de produtos estocados no trimestre',
    acaoKri: '- Plano de ação para revisão das estratégias de vendas e mkt\n- Plano de ação para revisão das estratégias de estocagem e logística',
    quemMede: 'Gestão de Operações e Financeiro',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: 'Atingimento das metas de vendas e diminuição das perdas de estoque',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R013',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Operação baseada em "Estoque Zero" com dependência direta de entregas realizadas por fabricantes e terceiros',
    ameaca: 'Quebra de estoque no fabricante, atrasos logísticos de terceiros e falta de integração de sistemas de rastreio em tempo real',
    descricaoRisco: 'Incerteza quanto ao cumprimento do objetivo estratégico de "Aumentar em 8% a recorrência das compras" e "Alcançar 26% mais clientes", devido ao alto volume de cancelamentos e devoluções inerentes ao modelo atual',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: 'Erosão da margem de lucro por custos de logística reversa, perda de clientes para concorrentes com estoque próprio e danos à imagem da marca',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Transferir',
    controles: 'Implementação de SLAs (Acordos de Nível de Serviço) mais rígidos com fornecedores; Integração sistêmica via API para visibilidade de estoque real do fabricante; Contratação de seguro para interrupção de suprimentos',
    responsavel: 'Diretora de Operações (COO)\n\nDiretora de Expansão/Vendas',
    prazo: '90 dias para renegociação de contratos com os 10 principais fornecedores',
    kri: 'Índice de cancelamento de pedidos por falta de produto superior a 5% do total de vendas mensal',
    acaoKri: 'Suspensão temporária do anúncio do produto e auditoria no processo de atualização de estoque do parceiro',
    quemMede: 'Gestão de Operações',
    quandoMede: 'Semanalmente',
    reducaoPretendida: 3,
    riscoResidual: 3,
    eficaciaTratamento: 'Através da redução do número de reclamações no "Reclame Aqui" e aumento no NPS (Net Promoter Score) da DAMACORP',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R014',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Falta de politica interna para desenvolvimento',
    ameaca: 'Utilização de repositorio online publico para armazenamento de codigos criticos',
    descricaoRisco: 'Armazenamento não autorizado de codigo-fonte ocasionando exposição acidental ou intencional, facilitando ataques, manipulação e vazamento de informações',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: '- Exposição do codigo-fonta da plataforma\n - Vazamento de credenciais e chaves\n- Facilitação de ataques ciber\n- Perda de propriedade intelectual\n- Inconformidade com LGPD',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar\n- Bloqueio de repositorios externos\n- Implementar reposotorio corporativo seguro\n - Implementação de autenticação forte (MFA)',
    controles: 'Mitigar\n-  Politica de desenvolvimento\n- Treinamentos colaborativos',
    responsavel: '',
    prazo: '',
    kri: '',
    acaoKri: '',
    quemMede: '',
    quandoMede: '',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R016',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Armazenamento inadequado de informações sensíveis (em repositórios online ou dispositivos BYOD) e acesso indiscriminado de agências de marketing aos dados de clientes',
    ameaca: 'Hackers (Ransomware), funcionários mal-intencionados (ex-colaboradores com acesso ao código/dados) ou fiscalização da ANPD',
    descricaoRisco: 'Incerteza quanto ao objetivo de "Aperfeiçoar a conformidade legal e regulatória" e à sustentabilidade do faturamento, devido ao risco de sanções judiciais e perda de confiança do consumidor',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 5,
    riscoInerente: 20,
    consequencia: 'Multas pesadas da ANPD, proibição de tratar dados (paralisando o e-commerce), processos de indenização cível e danos graves à reputação no "Reclame Aqui"',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Evitar',
    controles: 'Nomeação de um DPO (Data Protection Officer); Criptografia de dados sensíveis no Banco Oracle; Implementação de um portal de gestão de consentimento; Revisão de contratos com agências de marketing para limitar acessos via APIs controladas',
    responsavel: 'Especialista em Riscos Cyber\n\nDiretora de Operações',
    prazo: '45 dias para o mapeamento de dados (Data Mapping) e ajuste de acessos',
    kri: 'Qualquer detecção de download de banco de dados pela agência externa fora do padrão contratado ou acesso a dados de clientes via dispositivos pessoais de desenvolvedores',
    acaoKri: 'Bloqueio imediato das credenciais, notificação ao comitê de crise e auditoria forense nos logs de acesso',
    quemMede: 'Especialista em Riscos Cyber',
    quandoMede: 'Monitoramento contínuo (em tempo real)',
    reducaoPretendida: 4,
    riscoResidual: 3,
    eficaciaTratamento: 'Através de relatórios de auditoria de conformidade LGPD sem apontamentos críticos e ausência de incidentes de vazamento reportados em 12 meses',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R017',
    fonteDeRisco: 'FE - Mercado',
    descricaoFonte: 'Falha na custódia de informações estratégicas e falta de sigilo em parcerias com agências externas',
    ameaca: 'Espionagem industrial por concorrentes, acesso indevido da agência de marketing a dados confidenciais e vazamento de informações por colaboradores internos insatisfeitos',
    descricaoRisco: 'Incerteza quanto ao alcance da meta de "Aumentar a participação no mercado em 26% mais clientes em 5 anos", devido à antecipação das campanhas promocionais pela concorrência',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: 'Perda de faturamento projetado, obsolescência precoce de campanhas de marketing, redução da competitividade e perda de "market share"',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Evitar',
    controles: 'Implementação de termos de confidencialidade (NDA) rígidos com agências; Restrição de acesso a dados estratégicos (segregação de acessos); Monitoramento de tráfego de saída de dados (DLP - Data Loss Prevention)',
    responsavel: 'Diretora de Expansão e Vendas\n\nEspecialista em Riscos Cyber',
    prazo: '30 dias para revisão de acessos da agência de marketing',
    kri: 'Identificação de 1 campanha concorrente com similaridade superior a 80% lançada em até 48h antes da Damacorp',
    acaoKri: 'Troca imediata de credenciais de acesso, auditoria nos logs de quem acessou as peças da campanha e revisão do contrato com a agência',
    quemMede: 'Equipe de Marketing \n\nInteligência de Mercado',
    quandoMede: 'Diariamente (Monitoramento da concorrência)',
    reducaoPretendida: 3,
    riscoResidual: 2,
    eficaciaTratamento: 'Através do aumento da taxa de conversão das campanhas exclusivas e ausência de cópias idênticas no mercado nos próximos 6 meses',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R018',
    fonteDeRisco: 'FI - Diretoria / Liderança / Sócios',
    descricaoFonte: 'Conflitos societários, baixa coesão da liderança, críticas a auditorias e fragilidades de governança, gerando decisões inconsistentes e exposição reputacional.',
    ameaca: 'Denúncias públicas, crises de imagem e questionamentos de mercado/auditorias explorando a falta de alinhamento e transparência da alta gestão.',
    descricaoRisco: 'A possibilidade de que conflitos entre sócios, fragilidades de governança e exposições públicas comprometam metas estratégicas de crescimento, reputação, captação/valor (M&A) e eficiência, gerando perda de credibilidade, impacto em resultados e dificuldade de atingir os objetivos de mercado e clientes.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 3,
    impacto: 4,
    riscoInerente: 12,
    consequencia: 'Danos reputacionais e perda de credibilidade afetando auditorias, M&A, parceiros e resultados.',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Evitar',
    controles: 'Fortalecimento da governança (políticas, alçadas, comitês), código de ética e canal de denúncias; auditorias internas/externas reforçadas; monitoramento de mídia; ações corretivas sobre condutas; comunicação corporativa estruturada; seguro D&O',
    responsavel: 'CEO / Conselho de Administração, com apoio de Compliance e Jurídico no monitoramento.',
    prazo: '6 meses para implementação completa das estruturas de governança e monitoramento mensal dos indicadores críticos de reputação e conformidade.',
    kri: 'Aumento de denúncias relevantes, achados críticos recorrentes de auditoria e crescimento de menções negativas na mídia envolvendo sócios ou governança.',
    acaoKri: 'Acionar o protocolo de crise e governança: comunicação executiva transparente; abertura de apuração independente via Compliance/Jurídico; implementação imediata de medidas corretivas e de governança; resposta tempestiva a achados de auditoria; alinhamento com Conselho; e prestação de contas a stakeholders (investidores, auditorias e mercado).',
    quemMede: 'Compliance/Jurídico (canal de denúncias, prazos de apuração e achados), Auditoria Interna/Externa (achados e reincidências) e RI/Comunicação (monitoramento de menções negativas na mídia).',
    quandoMede: 'Mensalmente (relatório consolidado), com acompanhamento imediato/contínuo em caso de denúncias relevantes, achados críticos de auditoria ou pico de menções negativas na mídia.',
    reducaoPretendida: 3,
    riscoResidual: 5,
    eficaciaTratamento: 'Redução de denúncias relevantes sem resposta e de achados críticos recorrentes de auditoria; diminuição de menções negativas na mídia; melhoria do tempo de resposta a auditorias/órgãos e aderência às políticas de governança, comparados à linha de base anterior aos controles.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R019',
    fonteDeRisco: 'FI - Recursos Humanos e força de trabalho',
    descricaoFonte: 'Liderança de TI com mentalidade de "gestão por crise" e falta de vivência em e-commerce',
    ameaca: 'Conflitos internos entre a equipe técnica e o executivo de TI, desmotivação dos talentos e perda de conhecimento crítico',
    descricaoRisco: 'Incerteza quanto à capacidade de reter talentos e reduzir o turnover em 4%, devido a uma cultura organizacional que celebra o caos em vez da prevenção',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 3,
    riscoInerente: 12,
    consequencia: 'Aumento dos custos de recrutamento e treinamento, atrasos no desenvolvimento de novas funcionalidades e perda de capital intelectual para concorrentes',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Implementação de programas de desenvolvimento de liderança; Pesquisas de clima organizacional trimestrais; Reestruturação das metas de TI focadas em disponibilidade (prevenção) e não em resolução de crises',
    responsavel: 'Diretora de Operações\n\nRH',
    prazo: '180 dias para mudança cultural e novos KPIs',
    kri: 'Índice de turnover na equipe de TI superior a 10% em um semestre',
    acaoKri: 'Entrevistas de desligamento detalhadas e revisão da posição de liderança do executivo de TI',
    quemMede: 'Departamento de RH',
    quandoMede: 'Semestralmente',
    reducaoPretendida: 4,
    riscoResidual: 3,
    eficaciaTratamento: 'Através da melhoria nos índices de satisfação interna e redução de falhas operacionais evitáveis',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const RISKS_AULA4: Risk[] = [
  {
    id: 'R003',
    fonteDeRisco: 'FE - Fornecedores',
    descricaoFonte: 'Dependência critica do SAP-FI com baixa tolerância a falhas',
    ameaca: 'Interrupção do serviço pelo fornecedor',
    descricaoRisco: 'Indisponibilidade do SAP-FI entre os dias 25 a 30 de cada mês ocasionando parada no faturamento',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 2,
    impacto: 5,
    riscoInerente: 10,
    consequencia: '- Paralisação do faturamento\n- Atraso no fluzo de caixa\n- Risco de multas e/ou penalidades\n- Acumulo de operações e retrabalho\n- Impacto no EBITDA\n- Aumento de reclamação de clientes',
    gravidade: 4,
    urgencia: 5,
    tendencia: 3,
    gutScore: 60,
    tratamento: 'Mitigar - implementar Plano de Continuidade de Negócios com definição de RTO e RPO, incluindo procedimentos de contingência manual; realização de testes periodicos\nTransferir - acordo de co-responsabilidde com fornecedor',
    controles: 'Seguro cibernetico\nBackup',
    responsavel: 'Diretoria de Riscos e GCN',
    prazo: '365 dias',
    kri: '',
    acaoKri: '',
    quemMede: '',
    quandoMede: '',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R004',
    fonteDeRisco: 'FI - Seguranca, saude e meio ambiente',
    descricaoFonte: 'Segurança física dos DCs insuficientes no período noturno',
    ameaca: 'Assaltantes podem invadir o local, subtrair produtos, atingir colaboradores, paralisar a operação e impactar a imagem da instituição',
    descricaoRisco: 'Um assalto pode impactar a continuidade dos negócios e gerar prejuízos financeiros e operacionais.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Operacional',
    probabilidade: 3,
    impacto: 4,
    riscoInerente: 12,
    consequencia: '- Perda de produtos\n- Atrasos na operação\n- Afastamento de funcionarios\n- Impacto na imagem da organização\n- Maior probabilidade de novas ocorrencias',
    gravidade: 4,
    urgencia: 4,
    tendencia: 4,
    gutScore: 64,
    tratamento: 'Transferência e Mitigação',
    controles: 'Contratação de seguro patrimonial / Contratação de Segurança Externa para apoio em incidentes / Aumento do efetivo da segurança interna no período noturno / Ativação de sistema de CFVT no período noturno',
    responsavel: 'Diretor de Segurança',
    prazo: '3 meses',
    kri: 'KRI 1 - Número de tentativas de assaltos bem-sucedidas por mês = 2\nKRI 2 - Quantidade de horas de paralisação de produção por tentativas de assaltos por mês = 4h',
    acaoKri: 'Reavaliação das estruturas de segurança\nEntrevista com os envolvidos nos incidentes para coleta de dados para aperfeiçoamento das brechas',
    quemMede: 'Área de Riscos',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: 'Analise de eficacia dos sistemas e processos de segurança implementados',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R005',
    fonteDeRisco: 'FE - Cibersegurança ou Tecnologicas externas',
    descricaoFonte: 'Inexistência de uma estrutura formal de defesa cibernética e falta de governança de TI',
    ameaca: 'Agentes externos (hackers) podem explorar vunerabilidades no ambiente;  vazamento de dados por funcionários interno e indisponibilidade de sistemas críticos por falta de monitoramento',
    descricaoRisco: 'Um ataque racker pode vazar dados de clientes causando perda de reputação; Falta de gestão causando incerteza quanto à capacidade da empresa em proteger seus dados e manter a operação online',
    estrategico: 'SIM',
    tipoRisco: 'Risco Operacional',
    probabilidade: 4,
    impacto: 5,
    riscoInerente: 20,
    consequencia: 'Perda de receita por queda do site, multas regulatórias, perda de reputação e impedimento de processos de fusão/venda (M&A)',
    gravidade: 5,
    urgencia: 4,
    tendencia: 4,
    gutScore: 80,
    tratamento: 'Mitigar e Evitar',
    controles: 'Contratação imediata de um CISO ou consultoria especializada em GRC; implementação de Política de Segurança da Informação e segregação de funções entre Infraestrutura e Segurança',
    responsavel: 'Especialista em Segurança Digital e Riscos Cyber',
    prazo: '30 a 60 dias para contratação e diagnóstico inicial',
    kri: 'Tentativa de acesso não autorizado em repositórios de código ou falhas no SAP-FI por mais de 4 horas',
    acaoKri: 'Acionamento do Plano de Resposta a Incidentes (a ser criado) e isolamento de sistemas afetados',
    quemMede: 'Especialista em Segurança Digital',
    quandoMede: 'Tempo real (Monitoramento contínuo)',
    reducaoPretendida: 4,
    riscoResidual: 3,
    eficaciaTratamento: 'Através de Auditorias de TI e redução no número de incidentes de vazamento reportados nos próximos 6 meses',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R006',
    fonteDeRisco: 'FE - Clientes',
    descricaoFonte: 'Comportamento sensivél dos clientes frente ao mercado',
    ameaca: 'Falhas de entrega, erros de preços e inconsistências operacionais',
    descricaoRisco: 'Falha na entrega ou erro de precificação causando queda nas vendas devido a sensibilidade do cliente, o levando a realizar reclamações e/ou devoluções',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: 'Danos à reputação, perda de vendas, cancelamentos e devoluções, comprometendo objetivos de mercado e fidelização.',
    gravidade: 4,
    urgencia: 4,
    tendencia: 4,
    gutScore: 64,
    tratamento: 'Mitigar',
    controles: 'Padronização e dupla aprovação no cadastro de preços; melhoria dos SLAs com parceiros logísticos; monitoramento contínuo de reclamações, cancelamentos e devoluções; auditorias de preços e promoções; ajustes rápidos em erros identificados; acionamento de contingência logística; revisão de indicadores de satisfação e governança periódica com áreas responsáveis e parceiros.',
    responsavel: 'Diretoria Comercial / Experiência do Cliente (Owner). Corresponsáveis: Operações/Logística (SLA e OTIF), SAC (reclamações/NPS) e TI/Comercial (governança de preços e publicações).',
    prazo: '4 meses',
    kri: 'Aumento de reclamações acima da média histórica, taxa de cancelamentos superior a 5% e devoluções acima de 10% no mês.',
    acaoKri: 'Acionar plano de resposta ao cliente, corrigir imediatamente erros de preço ou falhas de entrega, comunicar clientes afetados, revisar SLAs com parceiros e priorizar casos críticos no SAC para reduzir impacto e recuperar confiança.',
    quemMede: 'SAC / Atendimento ao Cliente, com apoio das áreas Comercial e Operações (Logística).',
    quandoMede: 'Mensalmente, com acompanhamento semanal dos indicadores críticos de reclamações, cancelamentos e devoluções.',
    reducaoPretendida: 1,
    riscoResidual: 6,
    eficaciaTratamento: 'Por meio da redução consistente das reclamações dos clientes, diminuição das taxas de cancelamentos e devoluções, melhoria no cumprimento dos prazos de entrega (OTIF) e redução de erros de preços, verificados por meio de indicadores mensais comparados à linha de base anterior aos controles.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R007',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Inexistência do PCN para a infraestrutura da XYZ Cloud',
    ameaca: 'Falha no hardware dos servidores do DataCenter da XYZ Cloud',
    descricaoRisco: 'Falha no hardware dos servidores do DataCenter da XYZ Cloud causando indisponibilidade do ambiente produtivo da DAMACORP.',
    estrategico: 'NÃO',
    tipoRisco: 'Risco Tecnológico',
    probabilidade: 4,
    impacto: 5,
    riscoInerente: 20,
    consequencia: '- Perca de Clientes\n- Perca de Dados',
    gravidade: 5,
    urgencia: 5,
    tendencia: 4,
    gutScore: 100,
    tratamento: 'Mitigar',
    controles: 'Contratação imediata de uma consultoria especializada em Continuidade de Negócios, que possui como base a norma ISO22301, para a estruturação do SGCN, elaborando a Análise de Impacto de Negócio (BIA), Análise de Risco, Definição das Estratégias de Contingência (Tecnologia e Negócio) e elaboração dos testes das contingências mapeadas.',
    responsavel: 'Gestão de Tecnologia e Negócio',
    prazo: '150 a 180 dias para contratação e estruturação do SGCN',
    kri: 'KRI1 → Instabilidade do ambiente produtivo\nKRI2 → Alta latência do ambiente produtivo\nKRI3 → Indisponibilidade do ambiente produtivo',
    acaoKri: 'Acionamento do Plano de Continuidade de Negócios para recuperação da infraestrutura',
    quemMede: 'Equipe de Monitoramento;\nEquipe de Negócios;\nEquipe de Tecnologia;\nEquipe de Resposta a Incidentes.',
    quandoMede: 'Tempo real (Monitoramento contínuo)',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R008',
    fonteDeRisco: 'FE - Meio ambiente',
    descricaoFonte: 'Eventos climáticos severos',
    ameaca: 'Interdições de vias, enchentes, tempestades e alagamentos explorando a dependência logística e a vulnerabilidade dos DCs e das rotas de transporte]',
    descricaoRisco: 'Um enchente pode bloquear o processo logistico da entrega, causando interrupções e atrasos generalizados nas entregas e insastifação do cliente.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 3,
    impacto: 4,
    riscoInerente: 12,
    consequencia: 'Atrasos nas entregas, aumento de reclamações, cancelamentos e prejuízos, com impacto direto na reputação e nas vendas.',
    gravidade: 4,
    urgencia: 3,
    tendencia: 5,
    gutScore: 60,
    tratamento: 'Mitigar',
    controles: 'Plano de contingência climática com rotas alternativas e operadores adicionais; monitoramento meteorológico; acionamento imediato de transportadoras alternativas; comunicação proativa aos clientes; revisão de SLAs logísticos; análise de desempenho em clima severo e lições aprendidas.',
    responsavel: 'Diretoria de Operações (Logística',
    prazo: '3 meses para implantação do plano de contingência e ajustes de SLAs, com monitoramento semanal em períodos de chuva intensa.',
    kri: 'OTIF < 90%, aumento de reclamações por atraso e cancelamentos acima de 5% durante eventos climáticos.',
    acaoKri: 'Acionar contingência logística, priorizar entregas críticas, comunicar clientes afetados e revisar SLAs com transportadoras para restabelecer o nível de serviço.',
    quemMede: 'Operações / Logística (Owner da medição de OTIF e desempenho de transportadoras), com apoio do SAC/Atendimento (reclamações por atraso) e Comercial (promessas de prazo).',
    quandoMede: 'Mensalmente, com acompanhamento semanal dos indicadores críticos (OTIF por rota/região, reclamações por atraso e cancelamentos) durante períodos de chuva intensa.',
    reducaoPretendida: 3,
    riscoResidual: 4,
    eficaciaTratamento: 'Melhora do OTIF, redução de atrasos por clima, queda nas reclamações por entrega, diminuição de cancelamentos e devoluções, comparados à linha de base anterior.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R009',
    fonteDeRisco: 'FI - Diretoria / Liderança / Sócios',
    descricaoFonte: 'Conexão familiar de sócio com entidade envolvida em esquemas de corrupção e lavagem de dinheiro',
    ameaca: 'Investigações da Polícia Federal (Operações derivadas), bloqueio de contas judiciais, busca e apreensão nos CDs ou sede e desconfiança de investidores',
    descricaoRisco: 'Incerteza quanto à continuidade do negócio e manutenção da imagem institucional devido ao receio de "contágio" reputacional ou envolvimento indireto em processos de corrupção',
    estrategico: 'SIM',
    tipoRisco: 'Risco Reputacional',
    probabilidade: 3,
    impacto: 5,
    riscoInerente: 15,
    consequencia: 'Rescisão de contratos com fabricantes, recusa de crédito bancário, cancelamento de parcerias logísticas e impossibilidade de venda da empresa (M&A)',
    gravidade: 4,
    urgencia: 4,
    tendencia: 4,
    gutScore: 64,
    tratamento: 'Mitigar e Aceitar',
    controles: 'Implementação de um Programa de Compliance robusto; Canal de Denúncias externo; Auditoria independente (Big Four) para validar balanços; Cláusulas de Due Diligence rigorosas em novos contratos',
    responsavel: 'Direção Estratégica e Relações de Mercado',
    prazo: '90 dias para implementação do programa de integridade',
    kri: 'Citação do nome da DAMACORP ou de seus sócios em depoimentos, mídias ou investigações correlatas',
    acaoKri: 'Acionamento do Gabinete de Crise (Assessoria de Imprensa e Jurídico Criminalista) e afastamento preventivo do sócio de funções executivas',
    quemMede: 'Direção Estratégica',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 3,
    riscoResidual: 4,
    eficaciaTratamento: 'Através de notas de auditoria sem ressalvas e manutenção das linhas de crédito bancário operacionais',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R010',
    fonteDeRisco: 'FE - Cibersegurança ou Tecnologicas externas',
    descricaoFonte: 'Funcionarios mal intencionados',
    ameaca: 'Ataque, invasão, DOS',
    descricaoRisco: 'Ataque ou invasão devido a facilitação intencional de funcionario interno ocasionando alteração de preços de produtos caros',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 5,
    impacto: 5,
    riscoInerente: 25,
    consequencia: '- Perda financeira imediata\n - Aumento de cancelamento e reembolso\n- Interrupção de vendas para correção dos preços\n- Danos à reputação e imagem',
    gravidade: 5,
    urgencia: 5,
    tendencia: 5,
    gutScore: 125,
    tratamento: 'Mitigar\n- Implementação de controles rigorosos de acesso\n- Monitoramento contínuo\n- Desenvolvimento seguro (proibir BYOD; repositorios internos seguros; revisão de código)',
    controles: 'Implementação de monitoramento e detecção;\nControle de infraestrutura e rede (firwall, segmentação de rede, waf, etc)',
    responsavel: 'Segurança da Informação',
    prazo: '30 dias',
    kri: 'KRI 1 - monitoramento de acessos suspeitos;\nKRI 2 - contas com acesso privilegiados acima do necessario\nKRI 3 - acesso de terceiros sem contrato ativo',
    acaoKri: '',
    quemMede: 'Gestão de risco de TI',
    quandoMede: 'Semanalmente',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R011',
    fonteDeRisco: 'FE - Fornecedores',
    descricaoFonte: 'Ausência de processo de KYS dentro da DAMACORP',
    ameaca: 'Fraudes, corrupção, desvio de verba por parte do fornecedore',
    descricaoRisco: 'Contratação de fornecedores fraudulentos ocasionando fraudes na companhia.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Operacional',
    probabilidade: 5,
    impacto: 3,
    riscoInerente: 15,
    consequencia: '- Perca de Cliente;\n- Lavagem de dinheiro;\n- Multas;\n- Perda de marketshare;\n- Imagem afetada.',
    gravidade: 3,
    urgencia: 4,
    tendencia: 3,
    gutScore: 36,
    tratamento: 'Mitigar:\n- Implementar uma esteira de Homologação de Serviço de Terceiros na companhia;\n- Elaboração das áreas pareceristas;\n- Elaboração da esteira de fornecedores relevantes para a companhia;\n- Elaboração da gestão orçamentária para contratação de terceiros.',
    controles: 'Elaboração do processo de Homologação de Prestadores de Serviço, para definir os riscos que o prestador de serviço pode trazer para a companhia e definir quais prestadores não são recomendados a contratação.',
    responsavel: '- Governança de Terceiros;\n- Compliance;\n- Segurança da Informação;\n- Continuidade de Negócios;\n- Arquitetura de Tecnologia',
    prazo: '30 dias',
    kri: 'KRI1 → Fornecedor possui um risco alto ou acima conforme norma;\nKRI2 → Fornecedor possui histórico de indícios de trabalho infantil;\nKRI3 → Fornecedor não cumpre o mínimo da régua de risco estabelecida por cada área parecerista.',
    acaoKri: 'Plano de ação para o prestador de serviço se adequar as necessidades da companhia',
    quemMede: 'Áreas pareceristas',
    quandoMede: 'A cada avaliação',
    reducaoPretendida: 3,
    riscoResidual: 1,
    eficaciaTratamento: 'A conformidade dos prestadores de serviço conforme régua de risco.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R012',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Aumento da diversificação de produtos',
    ameaca: 'Aumento significativo da atuação das áreas de pesquisa, mkt e produção em mercados desconhecidos',
    descricaoRisco: 'A empresa pretende atuar em ramos diversificados, os quais não possui experiencia, dificultando o ganho de marketshare e adequação dos processos internos',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 3,
    impacto: 3,
    riscoInerente: 9,
    consequencia: '- Perda de clientes\n- Diminuição de faturamento\n- Aumento de custos de estoque',
    gravidade: 3,
    urgencia: 3,
    tendencia: 4,
    gutScore: 36,
    tratamento: 'Mitigar e Transferir',
    controles: '- Contratação de marketing externo de nicho específico dos novos produtos\n- Divisão do CD por tipo de produto',
    responsavel: 'Diretorias Comerciais e de Logistica',
    prazo: '3 meses',
    kri: '- Não atingimento dos objetivos de vendas durante 3 meses consecutivos\n- Aumento de 10% de perdas de produtos estocados no trimestre',
    acaoKri: '- Plano de ação para revisão das estratégias de vendas e mkt\n- Plano de ação para revisão das estratégias de estocagem e logística',
    quemMede: 'Gestão de Operações e Financeiro',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: 'Atingimento das metas de vendas e diminuição das perdas de estoque',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R013',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Operação baseada em "Estoque Zero" com dependência direta de entregas realizadas por fabricantes e terceiros',
    ameaca: 'Quebra de estoque no fabricante, atrasos logísticos de terceiros e falta de integração de sistemas de rastreio em tempo real',
    descricaoRisco: 'Incerteza quanto ao cumprimento do objetivo estratégico de "Aumentar em 8% a recorrência das compras" e "Alcançar 26% mais clientes", devido ao alto volume de cancelamentos e devoluções inerentes ao modelo atual',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: 'Erosão da margem de lucro por custos de logística reversa, perda de clientes para concorrentes com estoque próprio e danos à imagem da marca',
    gravidade: 4,
    urgencia: 3,
    tendencia: 3,
    gutScore: 36,
    tratamento: 'Mitigar e Transferir',
    controles: 'Implementação de SLAs (Acordos de Nível de Serviço) mais rígidos com fornecedores; Integração sistêmica via API para visibilidade de estoque real do fabricante; Contratação de seguro para interrupção de suprimentos',
    responsavel: 'Diretora de Operações (COO)\n\nDiretora de Expansão/Vendas',
    prazo: '90 dias para renegociação de contratos com os 10 principais fornecedores',
    kri: 'Índice de cancelamento de pedidos por falta de produto superior a 5% do total de vendas mensal',
    acaoKri: 'Suspensão temporária do anúncio do produto e auditoria no processo de atualização de estoque do parceiro',
    quemMede: 'Gestão de Operações',
    quandoMede: 'Semanalmente',
    reducaoPretendida: 3,
    riscoResidual: 3,
    eficaciaTratamento: 'Através da redução do número de reclamações no "Reclame Aqui" e aumento no NPS (Net Promoter Score) da DAMACORP',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R014',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Falta de politica interna para desenvolvimento',
    ameaca: 'Utilização de repositorio online publico para armazenamento de codigos criticos',
    descricaoRisco: 'Armazenamento não autorizado de codigo-fonte ocasionando exposição acidental ou intencional, facilitando ataques, manipulação e vazamento de informações',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: '- Exposição do codigo-fonta da plataforma\n - Vazamento de credenciais e chaves\n- Facilitação de ataques ciber\n- Perda de propriedade intelectual\n- Inconformidade com LGPD',
    gravidade: 5,
    urgencia: 5,
    tendencia: 5,
    gutScore: 125,
    tratamento: 'Mitigar\n- Bloqueio de repositorios externos\n- Implementar reposotorio corporativo seguro\n - Implementação de autenticação forte (MFA)',
    controles: 'Mitigar\n-  Politica de desenvolvimento\n- Treinamentos colaborativos',
    responsavel: '',
    prazo: '',
    kri: 'KRI1 - - Número de violações de política de desenvolvimento seguro\nKRI2 - Acessos a repositórios externos (GitHub/GitLab) pela rede corporativa\n\nKRI3 - - Tentativas de acesso ao repositório interno por IPs externos',
    acaoKri: '- Isolar o usuário e revogar todas as credenciais.\n- Bloquear imediatamente o tráfego para repositórios externos.',
    quemMede: 'Segurança da Informação',
    quandoMede: '',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R016',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Armazenamento inadequado de informações sensíveis (em repositórios online ou dispositivos BYOD) e acesso indiscriminado de agências de marketing aos dados de clientes',
    ameaca: 'Hackers (Ransomware), funcionários mal-intencionados (ex-colaboradores com acesso ao código/dados) ou fiscalização da ANPD',
    descricaoRisco: 'Incerteza quanto ao objetivo de "Aperfeiçoar a conformidade legal e regulatória" e à sustentabilidade do faturamento, devido ao risco de sanções judiciais e perda de confiança do consumidor',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 5,
    riscoInerente: 20,
    consequencia: 'Multas pesadas da ANPD, proibição de tratar dados (paralisando o e-commerce), processos de indenização cível e danos graves à reputação no "Reclame Aqui"',
    gravidade: 5,
    urgencia: 3,
    tendencia: 4,
    gutScore: 60,
    tratamento: 'Mitigar e Evitar',
    controles: 'Nomeação de um DPO (Data Protection Officer); Criptografia de dados sensíveis no Banco Oracle; Implementação de um portal de gestão de consentimento; Revisão de contratos com agências de marketing para limitar acessos via APIs controladas',
    responsavel: 'Especialista em Riscos Cyber\n\nDiretora de Operações',
    prazo: '45 dias para o mapeamento de dados (Data Mapping) e ajuste de acessos',
    kri: 'Qualquer detecção de download de banco de dados pela agência externa fora do padrão contratado ou acesso a dados de clientes via dispositivos pessoais de desenvolvedores',
    acaoKri: 'Bloqueio imediato das credenciais, notificação ao comitê de crise e auditoria forense nos logs de acesso',
    quemMede: 'Especialista em Riscos Cyber',
    quandoMede: 'Monitoramento contínuo (em tempo real)',
    reducaoPretendida: 4,
    riscoResidual: 3,
    eficaciaTratamento: 'Através de relatórios de auditoria de conformidade LGPD sem apontamentos críticos e ausência de incidentes de vazamento reportados em 12 meses',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R017',
    fonteDeRisco: 'FE - Mercado',
    descricaoFonte: 'Falha na custódia de informações estratégicas e falta de sigilo em parcerias com agências externas',
    ameaca: 'Espionagem industrial por concorrentes, acesso indevido da agência de marketing a dados confidenciais e vazamento de informações por colaboradores internos insatisfeitos',
    descricaoRisco: 'Incerteza quanto ao alcance da meta de "Aumentar a participação no mercado em 26% mais clientes em 5 anos", devido à antecipação das campanhas promocionais pela concorrência',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: 'Perda de faturamento projetado, obsolescência precoce de campanhas de marketing, redução da competitividade e perda de "market share"',
    gravidade: 4,
    urgencia: 4,
    tendencia: 3,
    gutScore: 48,
    tratamento: 'Mitigar e Evitar',
    controles: 'Implementação de termos de confidencialidade (NDA) rígidos com agências; Restrição de acesso a dados estratégicos (segregação de acessos); Monitoramento de tráfego de saída de dados (DLP - Data Loss Prevention)',
    responsavel: 'Diretora de Expansão e Vendas\n\nEspecialista em Riscos Cyber',
    prazo: '30 dias para revisão de acessos da agência de marketing',
    kri: 'Identificação de 1 campanha concorrente com similaridade superior a 80% lançada em até 48h antes da Damacorp',
    acaoKri: 'Troca imediata de credenciais de acesso, auditoria nos logs de quem acessou as peças da campanha e revisão do contrato com a agência',
    quemMede: 'Equipe de Marketing \n\nInteligência de Mercado',
    quandoMede: 'Diariamente (Monitoramento da concorrência)',
    reducaoPretendida: 3,
    riscoResidual: 2,
    eficaciaTratamento: 'Através do aumento da taxa de conversão das campanhas exclusivas e ausência de cópias idênticas no mercado nos próximos 6 meses',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R018',
    fonteDeRisco: 'FI - Diretoria / Liderança / Sócios',
    descricaoFonte: 'Conflitos societários, baixa coesão da liderança, críticas a auditorias e fragilidades de governança, gerando decisões inconsistentes e exposição reputacional.',
    ameaca: 'Denúncias públicas, crises de imagem e questionamentos de mercado/auditorias explorando a falta de alinhamento e transparência da alta gestão.',
    descricaoRisco: 'A possibilidade de que conflitos entre sócios, fragilidades de governança e exposições públicas comprometam metas estratégicas de crescimento, reputação, captação/valor (M&A) e eficiência, gerando perda de credibilidade, impacto em resultados e dificuldade de atingir os objetivos de mercado e clientes.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 3,
    impacto: 4,
    riscoInerente: 12,
    consequencia: 'Danos reputacionais e perda de credibilidade afetando auditorias, M&A, parceiros e resultados.',
    gravidade: 4,
    urgencia: 3,
    tendencia: 5,
    gutScore: 60,
    tratamento: 'Mitigar e Evitar',
    controles: 'Fortalecimento da governança (políticas, alçadas, comitês), código de ética e canal de denúncias; auditorias internas/externas reforçadas; monitoramento de mídia; ações corretivas sobre condutas; comunicação corporativa estruturada; seguro D&O',
    responsavel: 'CEO / Conselho de Administração, com apoio de Compliance e Jurídico no monitoramento.',
    prazo: '6 meses para implementação completa das estruturas de governança e monitoramento mensal dos indicadores críticos de reputação e conformidade.',
    kri: 'Aumento de denúncias relevantes, achados críticos recorrentes de auditoria e crescimento de menções negativas na mídia envolvendo sócios ou governança.',
    acaoKri: 'Acionar o protocolo de crise e governança: comunicação executiva transparente; abertura de apuração independente via Compliance/Jurídico; implementação imediata de medidas corretivas e de governança; resposta tempestiva a achados de auditoria; alinhamento com Conselho; e prestação de contas a stakeholders (investidores, auditorias e mercado).',
    quemMede: 'Compliance/Jurídico (canal de denúncias, prazos de apuração e achados), Auditoria Interna/Externa (achados e reincidências) e RI/Comunicação (monitoramento de menções negativas na mídia).',
    quandoMede: 'Mensalmente (relatório consolidado), com acompanhamento imediato/contínuo em caso de denúncias relevantes, achados críticos de auditoria ou pico de menções negativas na mídia.',
    reducaoPretendida: 3,
    riscoResidual: 5,
    eficaciaTratamento: 'Redução de denúncias relevantes sem resposta e de achados críticos recorrentes de auditoria; diminuição de menções negativas na mídia; melhoria do tempo de resposta a auditorias/órgãos e aderência às políticas de governança, comparados à linha de base anterior aos controles.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R019',
    fonteDeRisco: 'FI - Recursos Humanos e força de trabalho',
    descricaoFonte: 'Liderança de TI com mentalidade de "gestão por crise" e falta de vivência em e-commerce',
    ameaca: 'Conflitos internos entre a equipe técnica e o executivo de TI, desmotivação dos talentos e perda de conhecimento crítico',
    descricaoRisco: 'Incerteza quanto à capacidade de reter talentos e reduzir o turnover em 4%, devido a uma cultura organizacional que celebra o caos em vez da prevenção',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 3,
    riscoInerente: 12,
    consequencia: 'Aumento dos custos de recrutamento e treinamento, atrasos no desenvolvimento de novas funcionalidades e perda de capital intelectual para concorrentes',
    gravidade: 3,
    urgencia: 4,
    tendencia: 4,
    gutScore: 48,
    tratamento: 'Mitigar',
    controles: 'Implementação de programas de desenvolvimento de liderança; Pesquisas de clima organizacional trimestrais; Reestruturação das metas de TI focadas em disponibilidade (prevenção) e não em resolução de crises',
    responsavel: 'Diretora de Operações\n\nRH',
    prazo: '180 dias para mudança cultural e novos KPIs',
    kri: 'Índice de turnover na equipe de TI superior a 10% em um semestre',
    acaoKri: 'Entrevistas de desligamento detalhadas e revisão da posição de liderança do executivo de TI',
    quemMede: 'Departamento de RH',
    quandoMede: 'Semestralmente',
    reducaoPretendida: 4,
    riscoResidual: 3,
    eficaciaTratamento: 'Através da melhoria nos índices de satisfação interna e redução de falhas operacionais evitáveis',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R021',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Ausência de Plano de Continuidade de Negócios',
    ameaca: 'Um desastres fisicos no data center que atende a empresa',
    descricaoRisco: 'Um incêndio nas dependências do DC que atende a empresa causando indisponibilidade tecnologica',
    estrategico: 'SIM',
    tipoRisco: 'Risco Ambiental e Climático',
    probabilidade: 1,
    impacto: 4,
    riscoInerente: 4,
    consequencia: 'Paralização de operações; impactos financeiros; impactos regulatórios',
    gravidade: 4,
    urgencia: 4,
    tendencia: 2,
    gutScore: 32,
    tratamento: 'Mitigar',
    controles: 'Monitoramento do DataCenter; Teste de equipamento contra incêndio',
    responsavel: 'Diretoria TI - infraestrutura',
    prazo: '10 dias',
    kri: 'KRI1-Monitoramento de infraestrutura e energia no DC;\nKRI2-Segurança patrimonial (acessos não autorizados; porta corta-fogo; materiais inflamaveis)',
    acaoKri: 'Imediato: verificaçao da infraestrutura; validar se backup estão integros;  acionamento do plano de contingência; operar no site de contingência até recuperação',
    quemMede: 'Diretoria de TI/Facilities',
    quandoMede: 'Diariamente',
    reducaoPretendida: 2,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R022',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Vazamento de informação interna',
    ameaca: 'Funcionario com acessos priveligiados',
    descricaoRisco: 'Um funcionario com acesso alem do que necessário causando vazamento de campanhas internas ao concorrente',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 5,
    impacto: 4,
    riscoInerente: 20,
    consequencia: 'Impacto regulatório; LGPD',
    gravidade: 5,
    urgencia: 4,
    tendencia: 4,
    gutScore: 80,
    tratamento: 'Mitigar',
    controles: 'Revisão periodica de acessos; Código de conduta; Canal confidencial',
    responsavel: 'Segurança da Informação; Compliance e Juridico',
    prazo: '30 dias',
    kri: 'KRI1-Monitoramento de acessos;\nKRI2-Movimentação de dados;\nKRI3-Monitoramento de comportamento anômalo',
    acaoKri: 'Revisão de logs de usuarios envolvidos; validação de acesso; registro do evento; suspensão do acesso; isolamento de equipamento (notebook etc); acionamento do juridico e RH para disciplina',
    quemMede: 'Segurança da Informação; Compliance',
    quandoMede: 'Diariamente',
    reducaoPretendida: 2,
    riscoResidual: 2,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R023',
    fonteDeRisco: 'FI - Seguranca, saude e meio ambiente',
    descricaoFonte: 'Greve no entorno da sede ou filial',
    ameaca: 'Ativistas podem interditar ruas impedindo funcionarios de chegar à empresa',
    descricaoRisco: 'Uma greve impossibilitando funcionarios de chegar a empresa causando parada nos processos por falta de equipe',
    estrategico: 'SIM',
    tipoRisco: 'Risco Humano (Pessoas e Cultura Organizacional)',
    probabilidade: 1,
    impacto: 4,
    riscoInerente: 4,
    consequencia: 'Impacto nas operações',
    gravidade: 3,
    urgencia: 2,
    tendencia: 2,
    gutScore: 12,
    tratamento: 'Mitigar',
    controles: 'Acompanhamento de eventos externos; Comunicação interna; Uso de VPN para trabalho remoto',
    responsavel: 'Diretoria de Riscos, Compliance',
    prazo: '30 dias',
    kri: 'KRI1 -Relação Sindical;\nKRI2- Dependencia Operacional',
    acaoKri: 'Sala de crise para acompanhamento; Liberação para trabalho remoto; realocação de equipes; redistribuição de tarefas',
    quemMede: 'Diretoria de Riscos e Crises; RH e Juridico',
    quandoMede: 'Diariamente',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R024',
    fonteDeRisco: 'FE - Governo',
    descricaoFonte: 'Fiscalização intensificada pela ANPD (Autoridade Nacional de Proteção de Dados) e novas regulamentações de proteção de dados.',
    ameaca: 'Fiscalização e autuação pela ANPD',
    descricaoRisco: 'Fiscalização pela ANPD ocasionando multas de até 2% do faturamento e sanções por descumprimento da LGPD, devido à falta de proteção adequada de dados de clientes',
    estrategico: 'SIM',
    tipoRisco: 'Risco de Conformidade (Regulatório e Legal)',
    probabilidade: 3,
    impacto: 5,
    riscoInerente: 15,
    consequencia: 'Multas de até 2% do faturamento (R$7M), suspensão parcial de atividades de tratamento de dados, dano reputacional severo, perda de confiança de clientes e parceiros.',
    gravidade: 5,
    urgencia: 5,
    tendencia: 5,
    gutScore: 125,
    tratamento: 'Mitigar',
    controles: 'Nomeação de DPO, Programa de conformidade LGPD, Mapeamento de dados pessoais, Política de privacidade atualizada, Treinamento de colaboradores, Auditorias periódicas de privacidade.',
    responsavel: 'DPO / Jurídico',
    prazo: '6 meses',
    kri: 'Nível de conformidade LGPD (%); Número de reclamações de titulares; Tempo de resposta a solicitações DSAR',
    acaoKri: 'Acionar plano de adequação emergencial e notificar ANPD sobre medidas corretivas',
    quemMede: 'DPO',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 3,
    riscoResidual: 2,
    eficaciaTratamento: 'Resultado de auditorias de privacidade. Tempo de resposta a incidentes de dados. Nível de conformidade LGPD.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R025',
    fonteDeRisco: 'FI - RH',
    descricaoFonte: 'Ausência de profissional dedicado à segurança da informação na estrutura organizacional, com responsabilidades dispersas entre TI e outras áreas.',
    ameaca: 'Falta de monitoramento e resposta a incidentes de segurança',
    descricaoRisco: 'Ausência de profissional dedicado à segurança da informação ocasionando falta de monitoramento contínuo e resposta inadequada a incidentes cibernéticos, aumentando a exposição a ataques',
    estrategico: 'SIM',
    tipoRisco: 'Risco de Segurança da Informação (Cibernético)',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: 'Incidentes de segurança não detectados a tempo, aumento do tempo de resposta (MTTR), maior superfície de ataque, vulnerabilidades não corrigidas, possível comprometimento de dados.',
    gravidade: 4,
    urgencia: 5,
    tendencia: 5,
    gutScore: 100,
    tratamento: 'Mitigar e Evitar',
    controles: 'Contratação de CISO/profissional de SI, Implementação de SOC (próprio ou terceirizado), Ferramentas de SIEM, Política de segurança da informação, Programa de conscientização.',
    responsavel: 'CIO / RH',
    prazo: '3 meses',
    kri: 'Tempo médio de detecção de incidentes (MTTD); Número de vulnerabilidades não corrigidas; Cobertura de monitoramento de ativos',
    acaoKri: 'Contratar SOC terceirizado emergencial e iniciar processo seletivo para CISO',
    quemMede: 'CIO',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 3,
    riscoResidual: 2,
    eficaciaTratamento: 'MTTD/MTTR de incidentes. Cobertura de monitoramento. Número de vulnerabilidades críticas abertas.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R026',
    fonteDeRisco: 'FE - Fornecedores',
    descricaoFonte: 'Agência de marketing digital terceirizada com acesso diário a dados de clientes para realização de campanhas promocionais e segmentação.',
    ameaca: 'Vazamento de dados por agência de marketing',
    descricaoRisco: 'Agência de marketing digital acessando dados de clientes diariamente ocasionando risco de vazamento de dados pessoais e eventual descumprimento de LGPD',
    estrategico: 'SIM',
    tipoRisco: 'Risco de Conformidade (Regulatório e Legal)',
    probabilidade: 3,
    impacto: 4,
    riscoInerente: 12,
    consequencia: 'Vazamento de dados pessoais de clientes, multas LGPD, perda de confiança de clientes, dano reputacional, possíveis processos judiciais individuais e coletivos.',
    gravidade: 4,
    urgencia: 4,
    tendencia: 4,
    gutScore: 64,
    tratamento: 'Mitigar e Transferir',
    controles: 'Contrato com cláusulas de proteção de dados (DPA), Acesso restrito por API com dados anonimizados, Auditoria periódica da agência, Seguro cibernético, Monitoramento de acessos.',
    responsavel: 'DPO / Marketing',
    prazo: '3 meses',
    kri: 'Volume de dados compartilhados com agência; Número de acessos não autorizados; Resultado de auditorias na agência',
    acaoKri: 'Suspender acesso da agência e acionar plano de resposta a incidentes de dados',
    quemMede: 'DPO',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 2,
    riscoResidual: 2,
    eficaciaTratamento: 'Resultado de auditorias na agência. Nível de anonimização dos dados compartilhados. Conformidade contratual.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R027',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Operação logística baseada no conceito de estoque zero, onde os Centros de Distribuição funcionam como único estoque disponível.',
    ameaca: 'Ruptura de estoque em períodos de alta demanda',
    descricaoRisco: 'Operação com conceito de estoque zero ocasionando ruptura de estoque e incapacidade de atender demanda em picos sazonais (Black Friday, Natal), gerando perda de vendas',
    estrategico: 'SIM',
    tipoRisco: 'Risco Operacional',
    probabilidade: 3,
    impacto: 3,
    riscoInerente: 9,
    consequencia: 'Perda de vendas em períodos de alta demanda, insatisfação de clientes, aumento de cancelamentos, impacto no faturamento e na meta de crescimento de 26% em 5 anos.',
    gravidade: 3,
    urgencia: 3,
    tendencia: 3,
    gutScore: 27,
    tratamento: 'Mitigar e Aceitar',
    controles: 'Planejamento de demanda com IA/ML, Acordos com fornecedores para reposição rápida, Estoque de segurança para itens de alta rotação, Monitoramento de níveis de estoque em tempo real.',
    responsavel: 'Diretor de Operações',
    prazo: '6 meses',
    kri: 'Taxa de ruptura de estoque (%); Tempo médio de reposição; Nível de estoque de segurança por categoria',
    acaoKri: 'Ativar fornecedores alternativos e aumentar estoque de segurança temporariamente',
    quemMede: 'Gerente de Logística',
    quandoMede: 'Semanalmente',
    reducaoPretendida: 2,
    riscoResidual: 1,
    eficaciaTratamento: 'Taxa de atendimento de pedidos. Tempo de reposição. Perda de vendas por ruptura.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R028',
    fonteDeRisco: 'FI - Seguranca, saude e meio ambiente',
    descricaoFonte: 'Segurança patrimonial deficiente no CD de Barueri com uso de câmeras falsas e bonecos, quadro reduzido no período noturno.',
    ameaca: 'Roubo ou furto de produtos no Centro de Distribuição',
    descricaoRisco: 'Segurança patrimonial deficiente com câmeras falsas e bonecos ocasionando vulnerabilidade a roubos e furtos no CD de Barueri, com histórico de ocorrências anteriores',
    estrategico: 'NÃO',
    tipoRisco: 'Risco Operacional',
    probabilidade: 3,
    impacto: 3,
    riscoInerente: 9,
    consequencia: 'Perda de produtos e mercadorias, interrupção parcial de operações, custos com reposição, impacto na imagem, risco à integridade física de colaboradores.',
    gravidade: 3,
    urgencia: 4,
    tendencia: 3,
    gutScore: 36,
    tratamento: 'Mitigar',
    controles: 'Substituição de câmeras falsas por sistema CFTV real, Aumento do efetivo de segurança noturna, Contratação de segurança armada, Seguro patrimonial, Controle de acesso biométrico.',
    responsavel: 'Diretor de Segurança',
    prazo: '3 meses',
    kri: 'Número de ocorrências de furto/roubo por trimestre; Cobertura de CFTV (%); Tempo de resposta da segurança',
    acaoKri: 'Reforço imediato do efetivo de segurança e acionamento de seguro',
    quemMede: 'Gerente de Segurança',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 2,
    riscoResidual: 1,
    eficaciaTratamento: 'Redução de ocorrências. Cobertura de CFTV. Tempo de resposta a incidentes.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R029',
    fonteDeRisco: 'FI - Tecnologicas internas',
    descricaoFonte: 'Múltiplas interfaces de conexão com sistemas legados, ERPs, parceiros logísticos e plataformas de pagamento, sem padronização de segurança.',
    ameaca: 'Exploração de vulnerabilidades em interfaces de integração',
    descricaoRisco: 'Múltiplas interfaces de conexão com sistemas legados e parceiros ocasionando vulnerabilidades de segurança e falhas de integração que podem comprometer dados e operações',
    estrategico: 'SIM',
    tipoRisco: 'Risco Tecnológico',
    probabilidade: 3,
    impacto: 4,
    riscoInerente: 12,
    consequencia: 'Falhas de integração causando inconsistência de dados, vulnerabilidades exploráveis por atacantes, interrupção de fluxos de pagamento e logística.',
    gravidade: 3,
    urgencia: 3,
    tendencia: 4,
    gutScore: 36,
    tratamento: 'Mitigar',
    controles: 'API Gateway com autenticação e rate limiting, Monitoramento de integrações, Testes de segurança em interfaces, Padronização de protocolos, Documentação de integrações.',
    responsavel: 'CTO / Arquiteto de Sistemas',
    prazo: '6 meses',
    kri: 'Número de falhas de integração por mês; Vulnerabilidades identificadas em APIs; Tempo de indisponibilidade de integrações',
    acaoKri: 'Desativar interface comprometida e ativar modo de contingência',
    quemMede: 'CTO',
    quandoMede: 'Semanalmente',
    reducaoPretendida: 2,
    riscoResidual: 2,
    eficaciaTratamento: 'Taxa de disponibilidade de integrações. Número de vulnerabilidades críticas. Tempo de resolução de falhas.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R030',
    fonteDeRisco: 'FI - RH',
    descricaoFonte: 'Desenvolvedores utilizando repositórios online não autorizados (GitHub pessoal, Google Drive) para armazenar código-fonte e documentação técnica.',
    ameaca: 'Exposição de código-fonte e propriedade intelectual',
    descricaoRisco: 'Desenvolvedores armazenando código crítico em repositórios online não autorizados ocasionando exposição de propriedade intelectual e dados operacionais sensíveis',
    estrategico: 'SIM',
    tipoRisco: 'Risco de Segurança da Informação (Cibernético)',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: 'Exposição de código-fonte proprietário, vazamento de lógica de negócios, possível uso por concorrentes, comprometimento de credenciais hardcoded no código.',
    gravidade: 4,
    urgencia: 4,
    tendencia: 4,
    gutScore: 64,
    tratamento: 'Mitigar e Evitar',
    controles: 'Repositório corporativo obrigatório (GitLab/GitHub Enterprise), DLP para detecção de upload de código, Política de uso aceitável, Treinamento de desenvolvedores, Auditoria de repositórios.',
    responsavel: 'CTO / CISO',
    prazo: '3 meses',
    kri: 'Número de repositórios não autorizados detectados; Código-fonte encontrado em fontes externas; Conformidade com política de repositórios',
    acaoKri: 'Bloquear acesso a repositórios externos e migrar código para repositório corporativo',
    quemMede: 'CISO',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 3,
    riscoResidual: 1,
    eficaciaTratamento: 'Conformidade com política de repositórios. Número de incidentes de vazamento de código. Cobertura de DLP.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R031',
    fonteDeRisco: 'FE - Clientes',
    descricaoFonte: 'Alto volume de transações online com múltiplos meios de pagamento, atraindo fraudadores que utilizam cartões clonados, identidades falsas e engenharia social.',
    ameaca: 'Fraude em transações de e-commerce',
    descricaoRisco: 'Fraudes em transações de e-commerce por clientes mal-intencionados ocasionando chargebacks, perdas financeiras diretas e aumento de custos operacionais com disputas',
    estrategico: 'NÃO',
    tipoRisco: 'Risco Financeiro',
    probabilidade: 4,
    impacto: 3,
    riscoInerente: 12,
    consequencia: 'Perdas financeiras por chargebacks, aumento de taxas de processamento, possível bloqueio por operadoras de cartão, custos com investigação de fraudes.',
    gravidade: 3,
    urgencia: 4,
    tendencia: 4,
    gutScore: 48,
    tratamento: 'Mitigar e Transferir',
    controles: 'Sistema antifraude com ML/IA, Autenticação 3D Secure, Análise de comportamento de compra, Seguro contra fraudes, Equipe dedicada de prevenção a fraudes.',
    responsavel: 'CFO / Diretor de Pagamentos',
    prazo: '3 meses',
    kri: 'Taxa de chargeback (%); Volume financeiro de fraudes detectadas; Taxa de falsos positivos do antifraude',
    acaoKri: 'Ativar regras restritivas de antifraude e suspender meios de pagamento comprometidos',
    quemMede: 'Gerente de Pagamentos',
    quandoMede: 'Semanalmente',
    reducaoPretendida: 2,
    riscoResidual: 2,
    eficaciaTratamento: 'Taxa de chargeback vs. benchmark do setor. Precisão do sistema antifraude. Volume de fraudes evitadas.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export interface EvolutionChange {
  riskId: string;
  type: 'new' | 'modified' | 'unchanged';
  changes: string[];
}

export const EVOLUTION_SUMMARY: EvolutionChange[] = [
  { riskId: 'R003', type: 'modified', changes: ["Descricao da Fonte", "GUT Revisado"] },
  { riskId: 'R004', type: 'modified', changes: ["Descricao da Fonte", "GUT Revisado"] },
  { riskId: 'R005', type: 'modified', changes: ["Descricao", "Ameaca", "Descricao da Fonte", "GUT Revisado"] },
  { riskId: 'R006', type: 'modified', changes: ["Descricao", "Ameaca", "Descricao da Fonte", "GUT Revisado"] },
  { riskId: 'R007', type: 'modified', changes: ["Descricao", "Ameaca", "Fonte de Risco", "GUT Revisado"] },
  { riskId: 'R008', type: 'modified', changes: ["Descricao", "Ameaca", "Descricao da Fonte", "GUT Revisado"] },
  { riskId: 'R009', type: 'modified', changes: ["GUT Revisado"] },
  { riskId: 'R010', type: 'modified', changes: ["Descricao", "Ameaca", "Descricao da Fonte", "Controles", "KRI", "GUT Revisado"] },
  { riskId: 'R011', type: 'modified', changes: ["Descricao", "Ameaca", "Descricao da Fonte", "GUT Revisado"] },
  { riskId: 'R012', type: 'modified', changes: ["GUT Revisado"] },
  { riskId: 'R013', type: 'modified', changes: ["GUT Revisado"] },
  { riskId: 'R014', type: 'modified', changes: ["KRI", "GUT Revisado"] },
  { riskId: 'R016', type: 'modified', changes: ["GUT Revisado"] },
  { riskId: 'R017', type: 'modified', changes: ["GUT Revisado"] },
  { riskId: 'R018', type: 'modified', changes: ["GUT Revisado"] },
  { riskId: 'R019', type: 'modified', changes: ["GUT Revisado"] },
  { riskId: 'R021', type: 'new', changes: ['Novo risco adicionado'] },
  { riskId: 'R022', type: 'new', changes: ['Novo risco adicionado'] },
  { riskId: 'R023', type: 'new', changes: ['Novo risco adicionado'] },
  { riskId: 'R024', type: 'new', changes: ['Novo risco adicionado'] },
  { riskId: 'R025', type: 'new', changes: ['Novo risco adicionado'] },
  { riskId: 'R026', type: 'new', changes: ['Novo risco adicionado'] },
  { riskId: 'R027', type: 'new', changes: ['Novo risco adicionado'] },
  { riskId: 'R028', type: 'new', changes: ['Novo risco adicionado'] },
  { riskId: 'R029', type: 'new', changes: ['Novo risco adicionado'] },
  { riskId: 'R030', type: 'new', changes: ['Novo risco adicionado'] },
  { riskId: 'R031', type: 'new', changes: ['Novo risco adicionado'] },
];
