// Vetor Horizon - Dados Evolutivos (Aula 3 -> Aula 4)
import { Risk } from './models';

export const RISKS_AULA3: Risk[] = [
  {
    id: 'R001',
    fonteDeRisco: 'FE - Cibersegurança ou Tecnologicas externas',
    descricaoFonte: 'Exemplo: Uso de tecnologia desatualizada, fornecedor instável, políticas internas falhas.',
    ameaca: 'Exemplo: Um hacker (ameaça) pode explorar uma vulnerabilidade causada por software desatualizado (fonte de risco).',
    descricaoRisco: '✅ Forma 1: Um ataque ransomware contra servidores corporativos pode comprometer dados críticos da empresa, resultando em perda de informações essenciais, paralisação de operações e possíveis impactos financeiros e reputacionais. ✅ Forma 2: Um ataque ransomware explorando a vulnerabilidade de um software desatualizado pode criptografar dados corporativos, levando à indisponibilidade das informações e potenciais prejuízos financeiros e operacionais. ✅ Forma 3: Um ataque ransomware pode causar a perda de dados críticos, impactando a continuidade dos negócios e gerando prejuízos financeiros e operacionais.',
    estrategico: 'SIM',
    tipoRisco: 'Risco de Segurança da Informação (Cibernético)',
    probabilidade: 1,
    impacto: 4,
    riscoInerente: 4,
    consequencia: 'Comprometer dados críticos da empresa, resultando em perda de informações essenciais, paralisação de operações e possíveis impactos financeiros e reputacionais.',
    gravidade: 2,
    urgencia: 3,
    tendencia: 3,
    gutScore: 18,
    tratamento: 'Mitigar e Transferir',
    controles: '- Seguros cibernéticos\n- Backups seguros e criptografados (offline e na nuvem).\n- Monitoramento contínuo de segurança (SIEM, SOC, IDS/IPS).\n- Autenticação multifator (MFA) e controles de acesso rigorosos.\n- Treinamento de colaboradores para evitar ataques de engenharia social.\n- Planos de resposta a incidentes e continuidade de negócios (ISO 22301).',
    responsavel: 'CIO',
    prazo: '12 meses',
    kri: 'KRI 1 - Número de tentativas de ataque bem-sucedidas (exemplo: acessos não autorizados, malware detectado) = 2\nKRI 2 - Quantidade de credenciais comprometidas (monitoramento em dark web) = 2\n\nKRI 3 - Número de falhas em testes de penetração = 2',
    acaoKri: '?',
    quemMede: 'CIO',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 3,
    riscoResidual: 1,
    eficaciaTratamento: '✅ Seguro Cibernetico: Cobertura e tempo de resposta financeira após incidentes.\n- Indicadores de eficácia: Percentual do custo de um incidente coberto pelo seguro, e Tempo médio de reembolso após um sinistro ou Número de cláusulas acionáveis (quanto do seguro realmente protege).\nComparação entre perdas financeiras projetadas vs. perdas cobertas pelo seguro.\n💡 Teste recomendado: Simular um incidente e avaliar tempo de resposta e cobertura do seguro. ✅ Backups Seguros e Criptografados (Offline e n',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R002',
    fonteDeRisco: 'FE - Mercado',
    descricaoFonte: 'Exemplo: Flutuação cambial abrupta causada por fatores macroeconômicos, crises políticas ou instabilidade global. Exemplo: Uma crise econômica global ou instabilidade política interna faz com que o dólar aumente 15% em uma semana.',
    ameaca: 'Exemplo: Aumento inesperado no custo de importação',
    descricaoRisco: '✅ Forma 1: Uma flutuação abrupta no câmbio, com valorização excessiva da moeda estrangeira (dólar), pode aumentar os custos de importação da empresa, impactando a margem de lucro e reduzindo a competitividade dos produtos no mercado, podendo levar a perdas financeiras e queda nas vendas.\n ✅ Forma 2: A alta volatilidade do câmbio, aliada à ausência de hedge cambial e estratégias de proteção financeira, pode resultar em um aumento significativo nos custos de importação, comprometendo a viabilidade dos negócios, afetando preços e causando prejuízos operacionais.\n✅ Forma 3: Uma valorização abrupta da moeda estrangeira pode resultar no aumento dos custos de importação, impactando negativamente a margem de lucro da empresa e reduzindo sua competitividade no mercado.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 2,
    impacto: 4,
    riscoInerente: 8,
    consequencia: '✅ Aumento do custo de produtos importados, reduzindo margens de lucro.\n✅ Dificuldade em repassar os custos ao consumidor, podendo reduzir vendas.\n✅ Impacto no fluxo de caixa, pois as despesas em moeda estrangeira aumentam sem tempo de ajuste.\n✅ Possível endividamento, caso a empresa tenha financiamentos em moeda estrangeira.',
    gravidade: 4,
    urgencia: 3,
    tendencia: 3,
    gutScore: 36,
    tratamento: 'Mitigar',
    controles: '- Mitigar? (Mais recomendado!) ✅ Hedge cambial – Contratos futuros ou swaps para fixar a cotação de compra.\n✅ Diversificação de fornecedores – Buscar alternativas em outras moedas ou negociar contratos em moeda local.\n✅ Precificação dinâmica – Estratégia de reajuste de preços conforme flutuações cambiais.\n✅ Planejamento financeiro – Criar reservas para cobrir variações inesperadas.\n\nTransferência (Redução do Impacto Financeiro):\n✅ Contratar seguros cambiais para limitar as perdas.\n✅ Negociar com',
    responsavel: 'CFO',
    prazo: '',
    kri: 'InIndicadores para monitoramento da variação cambial:\n✅ Variação percentual do câmbio em relação ao planejamento (exemplo: dólar acima de 10% da projeção).\n✅ Tempo médio de impacto do câmbio no custo de importação (exemplo: quanto tempo leva para o aumento da moeda impactar preços finais).\n✅ Exposição cambial da empresa (% dos custos atrelados a moedas estrangeiras).\n✅ Percentual de hedge contratado sobre importações (quanto da operação está protegida contra flutuações).',
    acaoKri: '',
    quemMede: '',
    quandoMede: '',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R003',
    fonteDeRisco: 'FE - Fornecedores',
    descricaoFonte: 'Dependência de infraestrutura de fornecedor',
    ameaca: 'Interrupção do serviço pelo fornecedor',
    descricaoRisco: 'Indisponibilidade do SAP-FI entre os dias 25 a 30 de cada mês ocasionando parada no faturamento',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 2,
    impacto: 5,
    riscoInerente: 10,
    consequencia: '- Paralisação do faturamento\n- Atraso no fluzo de caixa\n- Risco de multas e/ou penalidades\n- Acumulo de operações e retrabalho\n- Impacto no EBITDA\n- Aumento de reclamação de clientes',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Transferir',
    controles: 'Seguro cibernetico\nBackup',
    responsavel: '',
    prazo: '',
    kri: '',
    acaoKri: '',
    quemMede: '',
    quandoMede: '',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R004',
    fonteDeRisco: 'FI - Seguranca, saude e meio ambiente',
    descricaoFonte: 'Segurança física dos CDs insuficientes no período noturno',
    ameaca: 'Assaltantes podem invadir o local, subtrair produtos, atingir colaboradores, paralisar a operação e impactar a imagem da instituição',
    descricaoRisco: 'Um assalto pode impactar a continuidade dos negócios e gerar prejuízos financeiros e operacionais.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Operacional',
    probabilidade: 3,
    impacto: 4,
    riscoInerente: 12,
    consequencia: '- Perda de produtos\n- Atrasos na operação\n- Afastamento de funcionarios\n- Impacto na imagem da organização\n- Maior probabilidade de novas ocorrencias',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Contratação de seguro patrimonial / Contratação de Segurança Externa para apoio em incidentes / Aumento do efetivo da segurança interna no período noturno / Ativação de sistema de CFVT no período noturno',
    responsavel: 'Diretor de Segurança',
    prazo: '3 meses',
    kri: 'KRI 1 - Número de tentativas de assaltos bem-sucedidas por mês = 2\nKRI 2 - Quantidade de horas de paralisação de produção por tentativas de assaltos por mês = 4h',
    acaoKri: 'Reavaliação das estruturas de segurança\nEntrevista com os envolvidos nos incidentes para coleta de dados para aperfeiçoamento das brechas',
    quemMede: 'Área de Riscos',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: 'Analise de eficacia dos sistemas e processos de segurança implementados',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R005',
    fonteDeRisco: 'FE - Cibersegurança ou Tecnologicas externas',
    descricaoFonte: 'Falta de governança de TI e inexistência de uma estrutura formal de defesa cibernética.',
    ameaca: 'Exploração de vulnerabilidades por agentes externos (hackers), vazamento de dados por funcionários e indisponibilidade de sistemas críticos por falta de monitoramento',
    descricaoRisco: 'Incerteza quanto à capacidade da empresa em proteger seus dados e manter a operação online devido à inexistência de um responsável técnico (CISO/Gestor de SI) para gerenciar as defesas',
    estrategico: 'SIM',
    tipoRisco: 'Risco Operacional',
    probabilidade: 4,
    impacto: 5,
    riscoInerente: 20,
    consequencia: 'Perda de receita por queda do site, multas regulatórias, perda de reputação e impedimento de processos de fusão/venda (M&A)',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Evitar',
    controles: 'Contratação imediata de um CISO ou consultoria especializada em GRC; implementação de Política de Segurança da Informação e segregação de funções entre Infraestrutura e Segurança',
    responsavel: 'Especialista em Segurança Digital e Riscos Cyber',
    prazo: '30 a 60 dias para contratação e diagnóstico inicial',
    kri: 'Tentativa de acesso não autorizado em repositórios de código ou falhas no SAP-FI por mais de 4 horas',
    acaoKri: 'Acionamento do Plano de Resposta a Incidentes (a ser criado) e isolamento de sistemas afetados',
    quemMede: 'Especialista em Segurança Digital',
    quandoMede: 'Tempo real (Monitoramento contínuo)',
    reducaoPretendida: 4,
    riscoResidual: 3,
    eficaciaTratamento: 'Através de Auditorias de TI e redução no número de incidentes de vazamento reportados nos próximos 6 meses',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R006',
    fonteDeRisco: 'FE - Clientes',
    descricaoFonte: 'Comportamento imprevisível dos clientes, aumento de reclamações por erros de preços, atrasos e falhas nas entregas',
    ameaca: 'Ação dos clientes insatisfeitos explorando falhas de entrega, erros de preços e inconsistências operacionais, resultando em reclamações públicas, cancelamentos e perda de confiança na marca.',
    descricaoRisco: 'A insatisfação dos clientes ocasionando queda nas vendas, aumento de cancelamentos e devoluções, piora na reputação e redução da fidelização, comprometendo os objetivos de crescimento de mercado, eficiência operacional e rentabilidade definidos pela empresa.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: 'Danos à reputação, perda de vendas, cancelamentos e devoluções, comprometendo objetivos de mercado e fidelização.',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Padronização e dupla aprovação no cadastro de preços; melhoria dos SLAs com parceiros logísticos; monitoramento contínuo de reclamações, cancelamentos e devoluções; auditorias de preços e promoções; ajustes rápidos em erros identificados; acionamento de contingência logística; revisão de indicadores de satisfação e governança periódica com áreas responsáveis e parceiros.',
    responsavel: 'Diretoria Comercial / Experiência do Cliente (Owner). Corresponsáveis: Operações/Logística (SLA e OTIF), SAC (reclamações/NPS) e TI/Comercial (governança de preços e publicações).',
    prazo: '4 meses',
    kri: 'Aumento de reclamações acima da média histórica, taxa de cancelamentos superior a 5% e devoluções acima de 10% no mês.',
    acaoKri: 'Acionar plano de resposta ao cliente, corrigir imediatamente erros de preço ou falhas de entrega, comunicar clientes afetados, revisar SLAs com parceiros e priorizar casos críticos no SAC para reduzir impacto e recuperar confiança.',
    quemMede: 'SAC / Atendimento ao Cliente, com apoio das áreas Comercial e Operações (Logística).',
    quandoMede: 'Mensalmente, com acompanhamento semanal dos indicadores críticos de reclamações, cancelamentos e devoluções.',
    reducaoPretendida: 1,
    riscoResidual: 6,
    eficaciaTratamento: 'Por meio da redução consistente das reclamações dos clientes, diminuição das taxas de cancelamentos e devoluções, melhoria no cumprimento dos prazos de entrega (OTIF) e redução de erros de preços, verificados por meio de indicadores mensais comparados à linha de base anterior aos controles.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R007',
    fonteDeRisco: 'FE - Cibersegurança ou Tecnologicas externas',
    descricaoFonte: 'Inexistência do PCN para a infraestrutura da XYZ Cloud',
    ameaca: 'Indisponibilidade do ambiente de produção da XYZ Cloud',
    descricaoRisco: 'Falha no hardware dos servidores do DataCenter da XYZ Cloud, que osaciona a indisponibilidade do ambiente produtivo da DAMACORP.',
    estrategico: 'NÃO',
    tipoRisco: 'Risco Tecnológico',
    probabilidade: 4,
    impacto: 5,
    riscoInerente: 20,
    consequencia: '- Perca de Clientes\n- Perca de Dados',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Contratação imediata de uma consultoria especializada em Continuidade de Negócios, que possui como base a norma ISO22301, para a estruturação do SGCN, elaborando a Análise de Impacto de Negócio (BIA), Análise de Risco, Definição das Estratégias de Contingência (Tecnologia e Negócio) e elaboração dos testes das contingências mapeadas.',
    responsavel: 'Gestão de Tecnologia e Negócio',
    prazo: '150 a 180 dias para contratação e estruturação do SGCN',
    kri: 'KRI1 → Instabilidade do ambiente produtivo\nKRI2 → Alta latência do ambiente produtivo\nKRI3 → Indisponibilidade do ambiente produtivo',
    acaoKri: 'Acionamento do Plano de Continuidade de Negócios para recuperação da infraestrutura',
    quemMede: 'Equipe de Monitoramento;\nEquipe de Negócios;\nEquipe de Tecnologia;\nEquipe de Resposta a Incidentes.',
    quandoMede: 'Tempo real (Monitoramento contínuo)',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R008',
    fonteDeRisco: 'FE - Meio ambiente',
    descricaoFonte: 'Eventos climáticos severos ocasionando atrasos e interrupções na logística, aumentando reclamações, cancelamentos e impactando vendas e reputação.',
    ameaca: 'Interdições de vias, enchentes, tempestades e alagamentos explorando a dependência logística e a vulnerabilidade dos CDs e das rotas de transporte, causando interrupções e atrasos generalizados nas entregas.',
    descricaoRisco: 'Incerteza sobre cumprir metas de satisfação, vendas e reputação devido a atrasos e interrupções logísticas causadas por eventos climáticos severos.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 3,
    impacto: 4,
    riscoInerente: 12,
    consequencia: 'Atrasos nas entregas, aumento de reclamações, cancelamentos e prejuízos, com impacto direto na reputação e nas vendas.',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Plano de contingência climática com rotas alternativas e operadores adicionais; monitoramento meteorológico; acionamento imediato de transportadoras alternativas; comunicação proativa aos clientes; revisão de SLAs logísticos; análise de desempenho em clima severo e lições aprendidas.',
    responsavel: 'Diretoria de Operações (Logística',
    prazo: '3 meses para implantação do plano de contingência e ajustes de SLAs, com monitoramento semanal em períodos de chuva intensa.',
    kri: 'OTIF < 90%, aumento de reclamações por atraso e cancelamentos acima de 5% durante eventos climáticos.',
    acaoKri: 'Acionar contingência logística, priorizar entregas críticas, comunicar clientes afetados e revisar SLAs com transportadoras para restabelecer o nível de serviço.',
    quemMede: 'Operações / Logística (Owner da medição de OTIF e desempenho de transportadoras), com apoio do SAC/Atendimento (reclamações por atraso) e Comercial (promessas de prazo).',
    quandoMede: 'Mensalmente, com acompanhamento semanal dos indicadores críticos (OTIF por rota/região, reclamações por atraso e cancelamentos) durante períodos de chuva intensa.',
    reducaoPretendida: 3,
    riscoResidual: 4,
    eficaciaTratamento: 'Melhora do OTIF, redução de atrasos por clima, queda nas reclamações por entrega, diminuição de cancelamentos e devoluções, comparados à linha de base anterior.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R009',
    fonteDeRisco: 'FI - Diretoria / Liderança / Sócios',
    descricaoFonte: 'Conexão familiar de sócio com entidade envolvida em esquemas de corrupção e lavagem de dinheiro',
    ameaca: 'Investigações da Polícia Federal (Operações derivadas), bloqueio de contas judiciais, busca e apreensão nos CDs ou sede e desconfiança de investidores',
    descricaoRisco: 'Incerteza quanto à continuidade do negócio e manutenção da imagem institucional devido ao receio de "contágio" reputacional ou envolvimento indireto em processos de corrupção',
    estrategico: 'SIM',
    tipoRisco: 'Risco Reputacional',
    probabilidade: 3,
    impacto: 5,
    riscoInerente: 15,
    consequencia: 'Rescisão de contratos com fabricantes, recusa de crédito bancário, cancelamento de parcerias logísticas e impossibilidade de venda da empresa (M&A)',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Aceitar',
    controles: 'Implementação de um Programa de Compliance robusto; Canal de Denúncias externo; Auditoria independente (Big Four) para validar balanços; Cláusulas de Due Diligence rigorosas em novos contratos',
    responsavel: 'Direção Estratégica e Relações de Mercado',
    prazo: '90 dias para implementação do programa de integridade',
    kri: 'Citação do nome da DAMACORP ou de seus sócios em depoimentos, mídias ou investigações correlatas',
    acaoKri: 'Acionamento do Gabinete de Crise (Assessoria de Imprensa e Jurídico Criminalista) e afastamento preventivo do sócio de funções executivas',
    quemMede: 'Direção Estratégica',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 3,
    riscoResidual: 4,
    eficaciaTratamento: 'Através de notas de auditoria sem ressalvas e manutenção das linhas de crédito bancário operacionais',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R010',
    fonteDeRisco: 'FE - Cibersegurança ou Tecnologicas externas',
    descricaoFonte: 'Ataque, invasão, DOS',
    ameaca: 'Facilitação por meio de envolvimento de funcionarios',
    descricaoRisco: 'Ataque ou invasão ocasionando alteração de preços de produtos caros',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 5,
    impacto: 5,
    riscoInerente: 25,
    consequencia: '- Perda financeira imediata\n - Aumento de cancelamento e reembolso\n- Interrupção de vendas para correção dos preços\n- Danos à reputação e imagem',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: '',
    responsavel: '',
    prazo: '',
    kri: '',
    acaoKri: '',
    quemMede: '',
    quandoMede: '',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R011',
    fonteDeRisco: 'FE - Fornecedores',
    descricaoFonte: 'Ausência do processo de KYS dentro da DAMACORP',
    ameaca: 'Fraudes internas, corrupção, desvio de verba.',
    descricaoRisco: 'Contratação de fornecedores fraudulentos que podem gerar fraudes na companhia.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Operacional',
    probabilidade: 5,
    impacto: 3,
    riscoInerente: 15,
    consequencia: '- Perca de Cliente;\n- Lavagem de dinheiro;\n- Multas;\n- Perda de marketshare;\n- Imagem afetada.',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Elaboração do processo de Homologação de Prestadores de Serviço, para definir os riscos que o prestador de serviço pode trazer para a companhia e definir quais prestadores não são recomendados a contratação.',
    responsavel: '- Governança de Terceiros;\n- Compliance;\n- Segurança da Informação;\n- Continuidade de Negócios;\n- Arquitetura de Tecnologia',
    prazo: '30 dias',
    kri: 'KRI1 → Fornecedor possui um risco alto ou acima conforme norma;\nKRI2 → Fornecedor possui histórico de indícios de trabalho infantil;\nKRI3 → Fornecedor não cumpre o mínimo da régua de risco estabelecida por cada área parecerista.',
    acaoKri: 'Plano de ação para o prestador de serviço se adequar as necessidades da companhia',
    quemMede: 'Áreas pareceristas',
    quandoMede: 'A cada avaliação',
    reducaoPretendida: 3,
    riscoResidual: 1,
    eficaciaTratamento: 'A conformidade dos prestadores de serviço conforme régua de risco.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R012',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Aumento da diversificação de produtos',
    ameaca: 'Aumento significativo da atuação das áreas de pesquisa, mkt e produção em mercados desconhecidos',
    descricaoRisco: 'A empresa pretende atuar em ramos diversificados, os quais não possui experiencia, dificultando o ganho de marketshare e adequação dos processos internos',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 3,
    impacto: 3,
    riscoInerente: 9,
    consequencia: '- Perda de clientes\n- Diminuição de faturamento\n- Aumento de custos de estoque',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Transferir',
    controles: '- Contratação de marketing externo de nicho específico dos novos produtos\n- Divisão do CD por tipo de produto',
    responsavel: 'Diretorias Comerciais e de Logistica',
    prazo: '3 meses',
    kri: '- Não atingimento dos objetivos de vendas durante 3 meses consecutivos\n- Aumento de 10% de perdas de produtos estocados no trimestre',
    acaoKri: '- Plano de ação para revisão das estratégias de vendas e mkt\n- Plano de ação para revisão das estratégias de estocagem e logística',
    quemMede: 'Gestão de Operações e Financeiro',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: 'Atingimento das metas de vendas e diminuição das perdas de estoque',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R013',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Operação baseada em "Estoque Zero" com dependência direta de entregas realizadas por fabricantes e terceiros',
    ameaca: 'Quebra de estoque no fabricante, atrasos logísticos de terceiros e falta de integração de sistemas de rastreio em tempo real',
    descricaoRisco: 'Incerteza quanto ao cumprimento do objetivo estratégico de "Aumentar em 8% a recorrência das compras" e "Alcançar 26% mais clientes", devido ao alto volume de cancelamentos e devoluções inerentes ao modelo atual',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: 'Erosão da margem de lucro por custos de logística reversa, perda de clientes para concorrentes com estoque próprio e danos à imagem da marca',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Transferir',
    controles: 'Implementação de SLAs (Acordos de Nível de Serviço) mais rígidos com fornecedores; Integração sistêmica via API para visibilidade de estoque real do fabricante; Contratação de seguro para interrupção de suprimentos',
    responsavel: 'Diretora de Operações (COO)\n\nDiretora de Expansão/Vendas',
    prazo: '90 dias para renegociação de contratos com os 10 principais fornecedores',
    kri: 'Índice de cancelamento de pedidos por falta de produto superior a 5% do total de vendas mensal',
    acaoKri: 'Suspensão temporária do anúncio do produto e auditoria no processo de atualização de estoque do parceiro',
    quemMede: 'Gestão de Operações',
    quandoMede: 'Semanalmente',
    reducaoPretendida: 3,
    riscoResidual: 3,
    eficaciaTratamento: 'Através da redução do número de reclamações no "Reclame Aqui" e aumento no NPS (Net Promoter Score) da DAMACORP',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R014',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Falta de politica interna para desenvolvimento',
    ameaca: 'Utilização de repositorio online publico para armazenamento de codigos criticos',
    descricaoRisco: 'Armazenamento não autorizado de codigo-fonte ocasionando exposição acidental ou intencional, facilitando ataques, manipulação e vazamento de informações',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: '- Exposição do codigo-fonta da plataforma\n - Vazamento de credenciais e chaves\n- Facilitação de ataques ciber\n- Perda de propriedade intelectual\n- Inconformidade com LGPD',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Mitigar\n-  Politica de desenvolvimento\n- Treinamentos colaborativos',
    responsavel: '',
    prazo: '',
    kri: '',
    acaoKri: '',
    quemMede: '',
    quandoMede: '',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R016',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Armazenamento inadequado de informações sensíveis (em repositórios online ou dispositivos BYOD) e acesso indiscriminado de agências de marketing aos dados de clientes',
    ameaca: 'Hackers (Ransomware), funcionários mal-intencionados (ex-colaboradores com acesso ao código/dados) ou fiscalização da ANPD',
    descricaoRisco: 'Incerteza quanto ao objetivo de "Aperfeiçoar a conformidade legal e regulatória" e à sustentabilidade do faturamento, devido ao risco de sanções judiciais e perda de confiança do consumidor',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 5,
    riscoInerente: 20,
    consequencia: 'Multas pesadas da ANPD, proibição de tratar dados (paralisando o e-commerce), processos de indenização cível e danos graves à reputação no "Reclame Aqui"',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Evitar',
    controles: 'Nomeação de um DPO (Data Protection Officer); Criptografia de dados sensíveis no Banco Oracle; Implementação de um portal de gestão de consentimento; Revisão de contratos com agências de marketing para limitar acessos via APIs controladas',
    responsavel: 'Especialista em Riscos Cyber\n\nDiretora de Operações',
    prazo: '45 dias para o mapeamento de dados (Data Mapping) e ajuste de acessos',
    kri: 'Qualquer detecção de download de banco de dados pela agência externa fora do padrão contratado ou acesso a dados de clientes via dispositivos pessoais de desenvolvedores',
    acaoKri: 'Bloqueio imediato das credenciais, notificação ao comitê de crise e auditoria forense nos logs de acesso',
    quemMede: 'Especialista em Riscos Cyber',
    quandoMede: 'Monitoramento contínuo (em tempo real)',
    reducaoPretendida: 4,
    riscoResidual: 3,
    eficaciaTratamento: 'Através de relatórios de auditoria de conformidade LGPD sem apontamentos críticos e ausência de incidentes de vazamento reportados em 12 meses',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R017',
    fonteDeRisco: 'FE - Mercado',
    descricaoFonte: 'Falha na custódia de informações estratégicas e falta de sigilo em parcerias com agências externas',
    ameaca: 'Espionagem industrial por concorrentes, acesso indevido da agência de marketing a dados confidenciais e vazamento de informações por colaboradores internos insatisfeitos',
    descricaoRisco: 'Incerteza quanto ao alcance da meta de "Aumentar a participação no mercado em 26% mais clientes em 5 anos", devido à antecipação das campanhas promocionais pela concorrência',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: 'Perda de faturamento projetado, obsolescência precoce de campanhas de marketing, redução da competitividade e perda de "market share"',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Evitar',
    controles: 'Implementação de termos de confidencialidade (NDA) rígidos com agências; Restrição de acesso a dados estratégicos (segregação de acessos); Monitoramento de tráfego de saída de dados (DLP - Data Loss Prevention)',
    responsavel: 'Diretora de Expansão e Vendas\n\nEspecialista em Riscos Cyber',
    prazo: '30 dias para revisão de acessos da agência de marketing',
    kri: 'Identificação de 1 campanha concorrente com similaridade superior a 80% lançada em até 48h antes da Damacorp',
    acaoKri: 'Troca imediata de credenciais de acesso, auditoria nos logs de quem acessou as peças da campanha e revisão do contrato com a agência',
    quemMede: 'Equipe de Marketing \n\nInteligência de Mercado',
    quandoMede: 'Diariamente (Monitoramento da concorrência)',
    reducaoPretendida: 3,
    riscoResidual: 2,
    eficaciaTratamento: 'Através do aumento da taxa de conversão das campanhas exclusivas e ausência de cópias idênticas no mercado nos próximos 6 meses',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R018',
    fonteDeRisco: 'FI - Diretoria / Liderança / Sócios',
    descricaoFonte: 'Conflitos societários, baixa coesão da liderança, críticas a auditorias e fragilidades de governança, gerando decisões inconsistentes e exposição reputacional.',
    ameaca: 'Denúncias públicas, crises de imagem e questionamentos de mercado/auditorias explorando a falta de alinhamento e transparência da alta gestão.',
    descricaoRisco: 'A possibilidade de que conflitos entre sócios, fragilidades de governança e exposições públicas comprometam metas estratégicas de crescimento, reputação, captação/valor (M&A) e eficiência, gerando perda de credibilidade, impacto em resultados e dificuldade de atingir os objetivos de mercado e clientes.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 3,
    impacto: 4,
    riscoInerente: 12,
    consequencia: 'Danos reputacionais e perda de credibilidade afetando auditorias, M&A, parceiros e resultados.',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Evitar',
    controles: 'Fortalecimento da governança (políticas, alçadas, comitês), código de ética e canal de denúncias; auditorias internas/externas reforçadas; monitoramento de mídia; ações corretivas sobre condutas; comunicação corporativa estruturada; seguro D&O',
    responsavel: 'CEO / Conselho de Administração, com apoio de Compliance e Jurídico no monitoramento.',
    prazo: '6 meses para implementação completa das estruturas de governança e monitoramento mensal dos indicadores críticos de reputação e conformidade.',
    kri: 'Aumento de denúncias relevantes, achados críticos recorrentes de auditoria e crescimento de menções negativas na mídia envolvendo sócios ou governança.',
    acaoKri: 'Acionar o protocolo de crise e governança: comunicação executiva transparente; abertura de apuração independente via Compliance/Jurídico; implementação imediata de medidas corretivas e de governança; resposta tempestiva a achados de auditoria; alinhamento com Conselho; e prestação de contas a stakeholders (investidores, auditorias e mercado).',
    quemMede: 'Compliance/Jurídico (canal de denúncias, prazos de apuração e achados), Auditoria Interna/Externa (achados e reincidências) e RI/Comunicação (monitoramento de menções negativas na mídia).',
    quandoMede: 'Mensalmente (relatório consolidado), com acompanhamento imediato/contínuo em caso de denúncias relevantes, achados críticos de auditoria ou pico de menções negativas na mídia.',
    reducaoPretendida: 3,
    riscoResidual: 5,
    eficaciaTratamento: 'Redução de denúncias relevantes sem resposta e de achados críticos recorrentes de auditoria; diminuição de menções negativas na mídia; melhoria do tempo de resposta a auditorias/órgãos e aderência às políticas de governança, comparados à linha de base anterior aos controles.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R019',
    fonteDeRisco: 'FI - Recursos Humanos e força de trabalho',
    descricaoFonte: 'Liderança de TI com mentalidade de "gestão por crise" e falta de vivência em e-commerce',
    ameaca: 'Conflitos internos entre a equipe técnica e o executivo de TI, desmotivação dos talentos e perda de conhecimento crítico',
    descricaoRisco: 'Incerteza quanto à capacidade de reter talentos e reduzir o turnover em 4%, devido a uma cultura organizacional que celebra o caos em vez da prevenção',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 3,
    riscoInerente: 12,
    consequencia: 'Aumento dos custos de recrutamento e treinamento, atrasos no desenvolvimento de novas funcionalidades e perda de capital intelectual para concorrentes',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Implementação de programas de desenvolvimento de liderança; Pesquisas de clima organizacional trimestrais; Reestruturação das metas de TI focadas em disponibilidade (prevenção) e não em resolução de crises',
    responsavel: 'Diretora de Operações\n\nRH',
    prazo: '180 dias para mudança cultural e novos KPIs',
    kri: 'Índice de turnover na equipe de TI superior a 10% em um semestre',
    acaoKri: 'Entrevistas de desligamento detalhadas e revisão da posição de liderança do executivo de TI',
    quemMede: 'Departamento de RH',
    quandoMede: 'Semestralmente',
    reducaoPretendida: 4,
    riscoResidual: 3,
    eficaciaTratamento: 'Através da melhoria nos índices de satisfação interna e redução de falhas operacionais evitáveis',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const RISKS_AULA4: Risk[] = [
  {
    id: 'R001',
    fonteDeRisco: 'FE - Cibersegurança ou Tecnologicas externas',
    descricaoFonte: 'Exemplo: Uso de tecnologia desatualizada, fornecedor instável, políticas internas falhas.',
    ameaca: 'Exemplo: Um hacker (ameaça) pode explorar uma vulnerabilidade causada por software desatualizado (fonte de risco).',
    descricaoRisco: '✅ Forma 1: Um ataque ransomware contra servidores corporativos pode comprometer dados críticos da empresa, resultando em perda de informações essenciais, paralisação de operações e possíveis impactos financeiros e reputacionais. ✅ Forma 2: Um ataque ransomware explorando a vulnerabilidade de um software desatualizado pode criptografar dados corporativos, levando à indisponibilidade das informações e potenciais prejuízos financeiros e operacionais. ✅ Forma 3: Um ataque ransomware pode causar a perda de dados críticos, impactando a continuidade dos negócios e gerando prejuízos financeiros e operacionais.',
    estrategico: 'SIM',
    tipoRisco: 'Risco de Segurança da Informação (Cibernético)',
    probabilidade: 1,
    impacto: 4,
    riscoInerente: 4,
    consequencia: 'Comprometer dados críticos da empresa, resultando em perda de informações essenciais, paralisação de operações e possíveis impactos financeiros e reputacionais.',
    gravidade: 2,
    urgencia: 3,
    tendencia: 3,
    gutScore: 18,
    tratamento: 'Mitigar e Transferir',
    controles: '- Seguros cibernéticos\n- Backups seguros e criptografados (offline e na nuvem).\n- Monitoramento contínuo de segurança (SIEM, SOC, IDS/IPS).\n- Autenticação multifator (MFA) e controles de acesso rigorosos.\n- Treinamento de colaboradores para evitar ataques de engenharia social.\n- Planos de resposta a incidentes e continuidade de negócios (ISO 22301).',
    responsavel: 'CIO',
    prazo: '12 meses',
    kri: 'KRI 1 - Número de tentativas de ataque bem-sucedidas (exemplo: acessos não autorizados, malware detectado) = 2\nKRI 2 - Quantidade de credenciais comprometidas (monitoramento em dark web) = 2\n\nKRI 3 - Número de falhas em testes de penetração = 2',
    acaoKri: '?',
    quemMede: 'CIO',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 3,
    riscoResidual: 1,
    eficaciaTratamento: '✅ Seguro Cibernetico: Cobertura e tempo de resposta financeira após incidentes.\n- Indicadores de eficácia: Percentual do custo de um incidente coberto pelo seguro, e Tempo médio de reembolso após um sinistro ou Número de cláusulas acionáveis (quanto do seguro realmente protege).\nComparação entre perdas financeiras projetadas vs. perdas cobertas pelo seguro.\n💡 Teste recomendado: Simular um incidente e avaliar tempo de resposta e cobertura do seguro. ✅ Backups Seguros e Criptografados (Offline e n',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R002',
    fonteDeRisco: 'FE - Mercado',
    descricaoFonte: 'Exemplo: Flutuação cambial abrupta causada por fatores macroeconômicos, crises políticas ou instabilidade global. Exemplo: Uma crise econômica global ou instabilidade política interna faz com que o dólar aumente 15% em uma semana.',
    ameaca: 'Exemplo: Aumento inesperado no custo de importação',
    descricaoRisco: '✅ Forma 1: Uma flutuação abrupta no câmbio, com valorização excessiva da moeda estrangeira (dólar), pode aumentar os custos de importação da empresa, impactando a margem de lucro e reduzindo a competitividade dos produtos no mercado, podendo levar a perdas financeiras e queda nas vendas.\n ✅ Forma 2: A alta volatilidade do câmbio, aliada à ausência de hedge cambial e estratégias de proteção financeira, pode resultar em um aumento significativo nos custos de importação, comprometendo a viabilidade dos negócios, afetando preços e causando prejuízos operacionais.\n✅ Forma 3: Uma valorização abrupta da moeda estrangeira pode resultar no aumento dos custos de importação, impactando negativamente a margem de lucro da empresa e reduzindo sua competitividade no mercado.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 2,
    impacto: 4,
    riscoInerente: 8,
    consequencia: '✅ Aumento do custo de produtos importados, reduzindo margens de lucro.\n✅ Dificuldade em repassar os custos ao consumidor, podendo reduzir vendas.\n✅ Impacto no fluxo de caixa, pois as despesas em moeda estrangeira aumentam sem tempo de ajuste.\n✅ Possível endividamento, caso a empresa tenha financiamentos em moeda estrangeira.',
    gravidade: 4,
    urgencia: 3,
    tendencia: 3,
    gutScore: 36,
    tratamento: 'Mitigar',
    controles: '- Mitigar? (Mais recomendado!) ✅ Hedge cambial – Contratos futuros ou swaps para fixar a cotação de compra.\n✅ Diversificação de fornecedores – Buscar alternativas em outras moedas ou negociar contratos em moeda local.\n✅ Precificação dinâmica – Estratégia de reajuste de preços conforme flutuações cambiais.\n✅ Planejamento financeiro – Criar reservas para cobrir variações inesperadas.\n\nTransferência (Redução do Impacto Financeiro):\n✅ Contratar seguros cambiais para limitar as perdas.\n✅ Negociar com',
    responsavel: 'CFO',
    prazo: '',
    kri: 'InIndicadores para monitoramento da variação cambial:\n✅ Variação percentual do câmbio em relação ao planejamento (exemplo: dólar acima de 10% da projeção).\n✅ Tempo médio de impacto do câmbio no custo de importação (exemplo: quanto tempo leva para o aumento da moeda impactar preços finais).\n✅ Exposição cambial da empresa (% dos custos atrelados a moedas estrangeiras).\n✅ Percentual de hedge contratado sobre importações (quanto da operação está protegida contra flutuações).',
    acaoKri: '',
    quemMede: '',
    quandoMede: '',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R003',
    fonteDeRisco: 'FE - Fornecedores',
    descricaoFonte: 'Dependência critica do SAP-FI com baixa tolerância a falhas',
    ameaca: 'Interrupção do serviço pelo fornecedor',
    descricaoRisco: 'Indisponibilidade do SAP-FI entre os dias 25 a 30 de cada mês ocasionando parada no faturamento',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 2,
    impacto: 5,
    riscoInerente: 10,
    consequencia: '- Paralisação do faturamento\n- Atraso no fluzo de caixa\n- Risco de multas e/ou penalidades\n- Acumulo de operações e retrabalho\n- Impacto no EBITDA\n- Aumento de reclamação de clientes',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Transferir',
    controles: 'Seguro cibernetico\nBackup',
    responsavel: 'Diretoria de Riscos e GCN',
    prazo: '365 dias',
    kri: '',
    acaoKri: '',
    quemMede: '',
    quandoMede: '',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R004',
    fonteDeRisco: 'FI - Seguranca, saude e meio ambiente',
    descricaoFonte: 'Segurança física dos DCs insuficientes no período noturno',
    ameaca: 'Assaltantes podem invadir o local, subtrair produtos, atingir colaboradores, paralisar a operação e impactar a imagem da instituição',
    descricaoRisco: 'Um assalto pode impactar a continuidade dos negócios e gerar prejuízos financeiros e operacionais.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Operacional',
    probabilidade: 3,
    impacto: 4,
    riscoInerente: 12,
    consequencia: '- Perda de produtos\n- Atrasos na operação\n- Afastamento de funcionarios\n- Impacto na imagem da organização\n- Maior probabilidade de novas ocorrencias',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Contratação de seguro patrimonial / Contratação de Segurança Externa para apoio em incidentes / Aumento do efetivo da segurança interna no período noturno / Ativação de sistema de CFVT no período noturno',
    responsavel: 'Diretor de Segurança',
    prazo: '3 meses',
    kri: 'KRI 1 - Número de tentativas de assaltos bem-sucedidas por mês = 2\nKRI 2 - Quantidade de horas de paralisação de produção por tentativas de assaltos por mês = 4h',
    acaoKri: 'Reavaliação das estruturas de segurança\nEntrevista com os envolvidos nos incidentes para coleta de dados para aperfeiçoamento das brechas',
    quemMede: 'Área de Riscos',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: 'Analise de eficacia dos sistemas e processos de segurança implementados',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R005',
    fonteDeRisco: 'FE - Cibersegurança ou Tecnologicas externas',
    descricaoFonte: 'Inexistência de uma estrutura formal de defesa cibernética e falta de governança de TI',
    ameaca: 'Agentes externos (hackers) podem explorar vunerabilidades no ambiente;  vazamento de dados por funcionários interno e indisponibilidade de sistemas críticos por falta de monitoramento',
    descricaoRisco: 'Um ataque racker pode vazar dados de clientes causando perda de reputação; Falta de gestão causando incerteza quanto à capacidade da empresa em proteger seus dados e manter a operação online',
    estrategico: 'SIM',
    tipoRisco: 'Risco Operacional',
    probabilidade: 4,
    impacto: 5,
    riscoInerente: 20,
    consequencia: 'Perda de receita por queda do site, multas regulatórias, perda de reputação e impedimento de processos de fusão/venda (M&A)',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Evitar',
    controles: 'Contratação imediata de um CISO ou consultoria especializada em GRC; implementação de Política de Segurança da Informação e segregação de funções entre Infraestrutura e Segurança',
    responsavel: 'Especialista em Segurança Digital e Riscos Cyber',
    prazo: '30 a 60 dias para contratação e diagnóstico inicial',
    kri: 'Tentativa de acesso não autorizado em repositórios de código ou falhas no SAP-FI por mais de 4 horas',
    acaoKri: 'Acionamento do Plano de Resposta a Incidentes (a ser criado) e isolamento de sistemas afetados',
    quemMede: 'Especialista em Segurança Digital',
    quandoMede: 'Tempo real (Monitoramento contínuo)',
    reducaoPretendida: 4,
    riscoResidual: 3,
    eficaciaTratamento: 'Através de Auditorias de TI e redução no número de incidentes de vazamento reportados nos próximos 6 meses',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R006',
    fonteDeRisco: 'FE - Clientes',
    descricaoFonte: 'Comportamento sensivél dos clientes frente ao mercado',
    ameaca: 'Falhas de entrega, erros de preços e inconsistências operacionais',
    descricaoRisco: 'Falha na entrega ou erro de precificação causando queda nas vendas devido a sensibilidade do cliente, o levando a realizar reclamações e/ou devoluções',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: 'Danos à reputação, perda de vendas, cancelamentos e devoluções, comprometendo objetivos de mercado e fidelização.',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Padronização e dupla aprovação no cadastro de preços; melhoria dos SLAs com parceiros logísticos; monitoramento contínuo de reclamações, cancelamentos e devoluções; auditorias de preços e promoções; ajustes rápidos em erros identificados; acionamento de contingência logística; revisão de indicadores de satisfação e governança periódica com áreas responsáveis e parceiros.',
    responsavel: 'Diretoria Comercial / Experiência do Cliente (Owner). Corresponsáveis: Operações/Logística (SLA e OTIF), SAC (reclamações/NPS) e TI/Comercial (governança de preços e publicações).',
    prazo: '4 meses',
    kri: 'Aumento de reclamações acima da média histórica, taxa de cancelamentos superior a 5% e devoluções acima de 10% no mês.',
    acaoKri: 'Acionar plano de resposta ao cliente, corrigir imediatamente erros de preço ou falhas de entrega, comunicar clientes afetados, revisar SLAs com parceiros e priorizar casos críticos no SAC para reduzir impacto e recuperar confiança.',
    quemMede: 'SAC / Atendimento ao Cliente, com apoio das áreas Comercial e Operações (Logística).',
    quandoMede: 'Mensalmente, com acompanhamento semanal dos indicadores críticos de reclamações, cancelamentos e devoluções.',
    reducaoPretendida: 1,
    riscoResidual: 6,
    eficaciaTratamento: 'Por meio da redução consistente das reclamações dos clientes, diminuição das taxas de cancelamentos e devoluções, melhoria no cumprimento dos prazos de entrega (OTIF) e redução de erros de preços, verificados por meio de indicadores mensais comparados à linha de base anterior aos controles.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R007',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Inexistência do PCN para a infraestrutura da XYZ Cloud',
    ameaca: 'Falha no hardware dos servidores do DataCenter da XYZ Cloud',
    descricaoRisco: 'Falha no hardware dos servidores do DataCenter da XYZ Cloud causando indisponibilidade do ambiente produtivo da DAMACORP.',
    estrategico: 'NÃO',
    tipoRisco: 'Risco Tecnológico',
    probabilidade: 4,
    impacto: 5,
    riscoInerente: 20,
    consequencia: '- Perca de Clientes\n- Perca de Dados',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Contratação imediata de uma consultoria especializada em Continuidade de Negócios, que possui como base a norma ISO22301, para a estruturação do SGCN, elaborando a Análise de Impacto de Negócio (BIA), Análise de Risco, Definição das Estratégias de Contingência (Tecnologia e Negócio) e elaboração dos testes das contingências mapeadas.',
    responsavel: 'Gestão de Tecnologia e Negócio',
    prazo: '150 a 180 dias para contratação e estruturação do SGCN',
    kri: 'KRI1 → Instabilidade do ambiente produtivo\nKRI2 → Alta latência do ambiente produtivo\nKRI3 → Indisponibilidade do ambiente produtivo',
    acaoKri: 'Acionamento do Plano de Continuidade de Negócios para recuperação da infraestrutura',
    quemMede: 'Equipe de Monitoramento;\nEquipe de Negócios;\nEquipe de Tecnologia;\nEquipe de Resposta a Incidentes.',
    quandoMede: 'Tempo real (Monitoramento contínuo)',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R008',
    fonteDeRisco: 'FE - Meio ambiente',
    descricaoFonte: 'Eventos climáticos severos',
    ameaca: 'Interdições de vias, enchentes, tempestades e alagamentos explorando a dependência logística e a vulnerabilidade dos DCs e das rotas de transporte]',
    descricaoRisco: 'Um enchente pode bloquear o processo logistico da entrega, causando interrupções e atrasos generalizados nas entregas e insastifação do cliente.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 3,
    impacto: 4,
    riscoInerente: 12,
    consequencia: 'Atrasos nas entregas, aumento de reclamações, cancelamentos e prejuízos, com impacto direto na reputação e nas vendas.',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Plano de contingência climática com rotas alternativas e operadores adicionais; monitoramento meteorológico; acionamento imediato de transportadoras alternativas; comunicação proativa aos clientes; revisão de SLAs logísticos; análise de desempenho em clima severo e lições aprendidas.',
    responsavel: 'Diretoria de Operações (Logística',
    prazo: '3 meses para implantação do plano de contingência e ajustes de SLAs, com monitoramento semanal em períodos de chuva intensa.',
    kri: 'OTIF < 90%, aumento de reclamações por atraso e cancelamentos acima de 5% durante eventos climáticos.',
    acaoKri: 'Acionar contingência logística, priorizar entregas críticas, comunicar clientes afetados e revisar SLAs com transportadoras para restabelecer o nível de serviço.',
    quemMede: 'Operações / Logística (Owner da medição de OTIF e desempenho de transportadoras), com apoio do SAC/Atendimento (reclamações por atraso) e Comercial (promessas de prazo).',
    quandoMede: 'Mensalmente, com acompanhamento semanal dos indicadores críticos (OTIF por rota/região, reclamações por atraso e cancelamentos) durante períodos de chuva intensa.',
    reducaoPretendida: 3,
    riscoResidual: 4,
    eficaciaTratamento: 'Melhora do OTIF, redução de atrasos por clima, queda nas reclamações por entrega, diminuição de cancelamentos e devoluções, comparados à linha de base anterior.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R009',
    fonteDeRisco: 'FI - Diretoria / Liderança / Sócios',
    descricaoFonte: 'Conexão familiar de sócio com entidade envolvida em esquemas de corrupção e lavagem de dinheiro',
    ameaca: 'Investigações da Polícia Federal (Operações derivadas), bloqueio de contas judiciais, busca e apreensão nos CDs ou sede e desconfiança de investidores',
    descricaoRisco: 'Incerteza quanto à continuidade do negócio e manutenção da imagem institucional devido ao receio de "contágio" reputacional ou envolvimento indireto em processos de corrupção',
    estrategico: 'SIM',
    tipoRisco: 'Risco Reputacional',
    probabilidade: 3,
    impacto: 5,
    riscoInerente: 15,
    consequencia: 'Rescisão de contratos com fabricantes, recusa de crédito bancário, cancelamento de parcerias logísticas e impossibilidade de venda da empresa (M&A)',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Aceitar',
    controles: 'Implementação de um Programa de Compliance robusto; Canal de Denúncias externo; Auditoria independente (Big Four) para validar balanços; Cláusulas de Due Diligence rigorosas em novos contratos',
    responsavel: 'Direção Estratégica e Relações de Mercado',
    prazo: '90 dias para implementação do programa de integridade',
    kri: 'Citação do nome da DAMACORP ou de seus sócios em depoimentos, mídias ou investigações correlatas',
    acaoKri: 'Acionamento do Gabinete de Crise (Assessoria de Imprensa e Jurídico Criminalista) e afastamento preventivo do sócio de funções executivas',
    quemMede: 'Direção Estratégica',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 3,
    riscoResidual: 4,
    eficaciaTratamento: 'Através de notas de auditoria sem ressalvas e manutenção das linhas de crédito bancário operacionais',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R010',
    fonteDeRisco: 'FE - Cibersegurança ou Tecnologicas externas',
    descricaoFonte: 'Funcionarios mal intencionados',
    ameaca: 'Ataque, invasão, DOS',
    descricaoRisco: 'Ataque ou invasão devido a facilitação intencional de funcionario interno ocasionando alteração de preços de produtos caros',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 5,
    impacto: 5,
    riscoInerente: 25,
    consequencia: '- Perda financeira imediata\n - Aumento de cancelamento e reembolso\n- Interrupção de vendas para correção dos preços\n- Danos à reputação e imagem',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Implementação de monitoramento e detecção;\nControle de infraestrutura e rede (firwall, segmentação de rede, waf, etc)',
    responsavel: 'Segurança da Informação',
    prazo: '30 dias',
    kri: 'KRI 1 - monitoramento de acessos suspeitos;\nKRI 2 - contas com acesso privilegiados acima do necessario\nKRI 3 - acesso de terceiros sem contrato ativo',
    acaoKri: '',
    quemMede: 'Gestão de risco de TI',
    quandoMede: 'Semanalmente',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R011',
    fonteDeRisco: 'FE - Fornecedores',
    descricaoFonte: 'Ausência de processo de KYS dentro da DAMACORP',
    ameaca: 'Fraudes, corrupção, desvio de verba por parte do fornecedore',
    descricaoRisco: 'Contratação de fornecedores fraudulentos ocasionando fraudes na companhia.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Operacional',
    probabilidade: 5,
    impacto: 3,
    riscoInerente: 15,
    consequencia: '- Perca de Cliente;\n- Lavagem de dinheiro;\n- Multas;\n- Perda de marketshare;\n- Imagem afetada.',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Elaboração do processo de Homologação de Prestadores de Serviço, para definir os riscos que o prestador de serviço pode trazer para a companhia e definir quais prestadores não são recomendados a contratação.',
    responsavel: '- Governança de Terceiros;\n- Compliance;\n- Segurança da Informação;\n- Continuidade de Negócios;\n- Arquitetura de Tecnologia',
    prazo: '30 dias',
    kri: 'KRI1 → Fornecedor possui um risco alto ou acima conforme norma;\nKRI2 → Fornecedor possui histórico de indícios de trabalho infantil;\nKRI3 → Fornecedor não cumpre o mínimo da régua de risco estabelecida por cada área parecerista.',
    acaoKri: 'Plano de ação para o prestador de serviço se adequar as necessidades da companhia',
    quemMede: 'Áreas pareceristas',
    quandoMede: 'A cada avaliação',
    reducaoPretendida: 3,
    riscoResidual: 1,
    eficaciaTratamento: 'A conformidade dos prestadores de serviço conforme régua de risco.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R012',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Aumento da diversificação de produtos',
    ameaca: 'Aumento significativo da atuação das áreas de pesquisa, mkt e produção em mercados desconhecidos',
    descricaoRisco: 'A empresa pretende atuar em ramos diversificados, os quais não possui experiencia, dificultando o ganho de marketshare e adequação dos processos internos',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 3,
    impacto: 3,
    riscoInerente: 9,
    consequencia: '- Perda de clientes\n- Diminuição de faturamento\n- Aumento de custos de estoque',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Transferir',
    controles: '- Contratação de marketing externo de nicho específico dos novos produtos\n- Divisão do CD por tipo de produto',
    responsavel: 'Diretorias Comerciais e de Logistica',
    prazo: '3 meses',
    kri: '- Não atingimento dos objetivos de vendas durante 3 meses consecutivos\n- Aumento de 10% de perdas de produtos estocados no trimestre',
    acaoKri: '- Plano de ação para revisão das estratégias de vendas e mkt\n- Plano de ação para revisão das estratégias de estocagem e logística',
    quemMede: 'Gestão de Operações e Financeiro',
    quandoMede: 'Mensalmente',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: 'Atingimento das metas de vendas e diminuição das perdas de estoque',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R013',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Operação baseada em "Estoque Zero" com dependência direta de entregas realizadas por fabricantes e terceiros',
    ameaca: 'Quebra de estoque no fabricante, atrasos logísticos de terceiros e falta de integração de sistemas de rastreio em tempo real',
    descricaoRisco: 'Incerteza quanto ao cumprimento do objetivo estratégico de "Aumentar em 8% a recorrência das compras" e "Alcançar 26% mais clientes", devido ao alto volume de cancelamentos e devoluções inerentes ao modelo atual',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: 'Erosão da margem de lucro por custos de logística reversa, perda de clientes para concorrentes com estoque próprio e danos à imagem da marca',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Transferir',
    controles: 'Implementação de SLAs (Acordos de Nível de Serviço) mais rígidos com fornecedores; Integração sistêmica via API para visibilidade de estoque real do fabricante; Contratação de seguro para interrupção de suprimentos',
    responsavel: 'Diretora de Operações (COO)\n\nDiretora de Expansão/Vendas',
    prazo: '90 dias para renegociação de contratos com os 10 principais fornecedores',
    kri: 'Índice de cancelamento de pedidos por falta de produto superior a 5% do total de vendas mensal',
    acaoKri: 'Suspensão temporária do anúncio do produto e auditoria no processo de atualização de estoque do parceiro',
    quemMede: 'Gestão de Operações',
    quandoMede: 'Semanalmente',
    reducaoPretendida: 3,
    riscoResidual: 3,
    eficaciaTratamento: 'Através da redução do número de reclamações no "Reclame Aqui" e aumento no NPS (Net Promoter Score) da DAMACORP',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R014',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Falta de politica interna para desenvolvimento',
    ameaca: 'Utilização de repositorio online publico para armazenamento de codigos criticos',
    descricaoRisco: 'Armazenamento não autorizado de codigo-fonte ocasionando exposição acidental ou intencional, facilitando ataques, manipulação e vazamento de informações',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: '- Exposição do codigo-fonta da plataforma\n - Vazamento de credenciais e chaves\n- Facilitação de ataques ciber\n- Perda de propriedade intelectual\n- Inconformidade com LGPD',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Mitigar\n-  Politica de desenvolvimento\n- Treinamentos colaborativos',
    responsavel: '',
    prazo: '',
    kri: 'KRI1 - - Número de violações de política de desenvolvimento seguro\nKRI2 - Acessos a repositórios externos (GitHub/GitLab) pela rede corporativa\n\nKRI3 - - Tentativas de acesso ao repositório interno por IPs externos',
    acaoKri: '- Isolar o usuário e revogar todas as credenciais.\n- Bloquear imediatamente o tráfego para repositórios externos.',
    quemMede: 'Segurança da Informação',
    quandoMede: '',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R016',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Armazenamento inadequado de informações sensíveis (em repositórios online ou dispositivos BYOD) e acesso indiscriminado de agências de marketing aos dados de clientes',
    ameaca: 'Hackers (Ransomware), funcionários mal-intencionados (ex-colaboradores com acesso ao código/dados) ou fiscalização da ANPD',
    descricaoRisco: 'Incerteza quanto ao objetivo de "Aperfeiçoar a conformidade legal e regulatória" e à sustentabilidade do faturamento, devido ao risco de sanções judiciais e perda de confiança do consumidor',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 5,
    riscoInerente: 20,
    consequencia: 'Multas pesadas da ANPD, proibição de tratar dados (paralisando o e-commerce), processos de indenização cível e danos graves à reputação no "Reclame Aqui"',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Evitar',
    controles: 'Nomeação de um DPO (Data Protection Officer); Criptografia de dados sensíveis no Banco Oracle; Implementação de um portal de gestão de consentimento; Revisão de contratos com agências de marketing para limitar acessos via APIs controladas',
    responsavel: 'Especialista em Riscos Cyber\n\nDiretora de Operações',
    prazo: '45 dias para o mapeamento de dados (Data Mapping) e ajuste de acessos',
    kri: 'Qualquer detecção de download de banco de dados pela agência externa fora do padrão contratado ou acesso a dados de clientes via dispositivos pessoais de desenvolvedores',
    acaoKri: 'Bloqueio imediato das credenciais, notificação ao comitê de crise e auditoria forense nos logs de acesso',
    quemMede: 'Especialista em Riscos Cyber',
    quandoMede: 'Monitoramento contínuo (em tempo real)',
    reducaoPretendida: 4,
    riscoResidual: 3,
    eficaciaTratamento: 'Através de relatórios de auditoria de conformidade LGPD sem apontamentos críticos e ausência de incidentes de vazamento reportados em 12 meses',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R017',
    fonteDeRisco: 'FE - Mercado',
    descricaoFonte: 'Falha na custódia de informações estratégicas e falta de sigilo em parcerias com agências externas',
    ameaca: 'Espionagem industrial por concorrentes, acesso indevido da agência de marketing a dados confidenciais e vazamento de informações por colaboradores internos insatisfeitos',
    descricaoRisco: 'Incerteza quanto ao alcance da meta de "Aumentar a participação no mercado em 26% mais clientes em 5 anos", devido à antecipação das campanhas promocionais pela concorrência',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 4,
    riscoInerente: 16,
    consequencia: 'Perda de faturamento projetado, obsolescência precoce de campanhas de marketing, redução da competitividade e perda de "market share"',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Evitar',
    controles: 'Implementação de termos de confidencialidade (NDA) rígidos com agências; Restrição de acesso a dados estratégicos (segregação de acessos); Monitoramento de tráfego de saída de dados (DLP - Data Loss Prevention)',
    responsavel: 'Diretora de Expansão e Vendas\n\nEspecialista em Riscos Cyber',
    prazo: '30 dias para revisão de acessos da agência de marketing',
    kri: 'Identificação de 1 campanha concorrente com similaridade superior a 80% lançada em até 48h antes da Damacorp',
    acaoKri: 'Troca imediata de credenciais de acesso, auditoria nos logs de quem acessou as peças da campanha e revisão do contrato com a agência',
    quemMede: 'Equipe de Marketing \n\nInteligência de Mercado',
    quandoMede: 'Diariamente (Monitoramento da concorrência)',
    reducaoPretendida: 3,
    riscoResidual: 2,
    eficaciaTratamento: 'Através do aumento da taxa de conversão das campanhas exclusivas e ausência de cópias idênticas no mercado nos próximos 6 meses',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R018',
    fonteDeRisco: 'FI - Diretoria / Liderança / Sócios',
    descricaoFonte: 'Conflitos societários, baixa coesão da liderança, críticas a auditorias e fragilidades de governança, gerando decisões inconsistentes e exposição reputacional.',
    ameaca: 'Denúncias públicas, crises de imagem e questionamentos de mercado/auditorias explorando a falta de alinhamento e transparência da alta gestão.',
    descricaoRisco: 'A possibilidade de que conflitos entre sócios, fragilidades de governança e exposições públicas comprometam metas estratégicas de crescimento, reputação, captação/valor (M&A) e eficiência, gerando perda de credibilidade, impacto em resultados e dificuldade de atingir os objetivos de mercado e clientes.',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 3,
    impacto: 4,
    riscoInerente: 12,
    consequencia: 'Danos reputacionais e perda de credibilidade afetando auditorias, M&A, parceiros e resultados.',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar e Evitar',
    controles: 'Fortalecimento da governança (políticas, alçadas, comitês), código de ética e canal de denúncias; auditorias internas/externas reforçadas; monitoramento de mídia; ações corretivas sobre condutas; comunicação corporativa estruturada; seguro D&O',
    responsavel: 'CEO / Conselho de Administração, com apoio de Compliance e Jurídico no monitoramento.',
    prazo: '6 meses para implementação completa das estruturas de governança e monitoramento mensal dos indicadores críticos de reputação e conformidade.',
    kri: 'Aumento de denúncias relevantes, achados críticos recorrentes de auditoria e crescimento de menções negativas na mídia envolvendo sócios ou governança.',
    acaoKri: 'Acionar o protocolo de crise e governança: comunicação executiva transparente; abertura de apuração independente via Compliance/Jurídico; implementação imediata de medidas corretivas e de governança; resposta tempestiva a achados de auditoria; alinhamento com Conselho; e prestação de contas a stakeholders (investidores, auditorias e mercado).',
    quemMede: 'Compliance/Jurídico (canal de denúncias, prazos de apuração e achados), Auditoria Interna/Externa (achados e reincidências) e RI/Comunicação (monitoramento de menções negativas na mídia).',
    quandoMede: 'Mensalmente (relatório consolidado), com acompanhamento imediato/contínuo em caso de denúncias relevantes, achados críticos de auditoria ou pico de menções negativas na mídia.',
    reducaoPretendida: 3,
    riscoResidual: 5,
    eficaciaTratamento: 'Redução de denúncias relevantes sem resposta e de achados críticos recorrentes de auditoria; diminuição de menções negativas na mídia; melhoria do tempo de resposta a auditorias/órgãos e aderência às políticas de governança, comparados à linha de base anterior aos controles.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R019',
    fonteDeRisco: 'FI - Recursos Humanos e força de trabalho',
    descricaoFonte: 'Liderança de TI com mentalidade de "gestão por crise" e falta de vivência em e-commerce',
    ameaca: 'Conflitos internos entre a equipe técnica e o executivo de TI, desmotivação dos talentos e perda de conhecimento crítico',
    descricaoRisco: 'Incerteza quanto à capacidade de reter talentos e reduzir o turnover em 4%, devido a uma cultura organizacional que celebra o caos em vez da prevenção',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 4,
    impacto: 3,
    riscoInerente: 12,
    consequencia: 'Aumento dos custos de recrutamento e treinamento, atrasos no desenvolvimento de novas funcionalidades e perda de capital intelectual para concorrentes',
    gravidade: 2,
    urgencia: 2,
    tendencia: 2,
    gutScore: 8,
    tratamento: 'Mitigar',
    controles: 'Implementação de programas de desenvolvimento de liderança; Pesquisas de clima organizacional trimestrais; Reestruturação das metas de TI focadas em disponibilidade (prevenção) e não em resolução de crises',
    responsavel: 'Diretora de Operações\n\nRH',
    prazo: '180 dias para mudança cultural e novos KPIs',
    kri: 'Índice de turnover na equipe de TI superior a 10% em um semestre',
    acaoKri: 'Entrevistas de desligamento detalhadas e revisão da posição de liderança do executivo de TI',
    quemMede: 'Departamento de RH',
    quandoMede: 'Semestralmente',
    reducaoPretendida: 4,
    riscoResidual: 3,
    eficaciaTratamento: 'Através da melhoria nos índices de satisfação interna e redução de falhas operacionais evitáveis',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R021',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Ausência de Plano de Continuidade de Negócios',
    ameaca: 'Um desastres fisicos no data center que atende a empresa',
    descricaoRisco: 'Um incêndio nas dependências do DC que atende a empresa causando indisponibilidade tecnologica',
    estrategico: 'SIM',
    tipoRisco: 'Risco Ambiental e Climático',
    probabilidade: 1,
    impacto: 4,
    riscoInerente: 4,
    consequencia: 'Paralização de operações; impactos financeiros; impactos regulatórios',
    gravidade: 4,
    urgencia: 4,
    tendencia: 2,
    gutScore: 32,
    tratamento: 'Mitigar',
    controles: 'Monitoramento do DataCenter; Teste de equipamento contra incêndio',
    responsavel: 'Diretoria TI - infraestrutura',
    prazo: '10 dias',
    kri: 'KRI1-Monitoramento de infraestrutura e energia no DC;\nKRI2-Segurança patrimonial (acessos não autorizados; porta corta-fogo; materiais inflamaveis)',
    acaoKri: 'Imediato: verificaçao da infraestrutura; validar se backup estão integros;  acionamento do plano de contingência; operar no site de contingência até recuperação',
    quemMede: 'Diretoria de TI/Facilities',
    quandoMede: 'Diariamente',
    reducaoPretendida: 2,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R022',
    fonteDeRisco: 'FI - Processos internos',
    descricaoFonte: 'Vazamento de informação interna',
    ameaca: 'Funcionario com acessos priveligiados',
    descricaoRisco: 'Um funcionario com acesso alem do que necessário causando vazamento de campanhas internas ao concorrente',
    estrategico: 'SIM',
    tipoRisco: 'Risco Estratégico',
    probabilidade: 5,
    impacto: 4,
    riscoInerente: 20,
    consequencia: 'Impacto regulatório; LGPD',
    gravidade: 5,
    urgencia: 4,
    tendencia: 4,
    gutScore: 80,
    tratamento: 'Mitigar',
    controles: 'Revisão periodica de acessos; Código de conduta; Canal confidencial',
    responsavel: 'Segurança da Informação; Compliance e Juridico',
    prazo: '30 dias',
    kri: 'KRI1-Monitoramento de acessos;\nKRI2-Movimentação de dados;\nKRI3-Monitoramento de comportamento anômalo',
    acaoKri: 'Revisão de logs de usuarios envolvidos; validação de acesso; registro do evento; suspensão do acesso; isolamento de equipamento (notebook etc); acionamento do juridico e RH para disciplina',
    quemMede: 'Segurança da Informação; Compliance',
    quandoMede: 'Diariamente',
    reducaoPretendida: 2,
    riscoResidual: 2,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'R023',
    fonteDeRisco: 'FI - Seguranca, saude e meio ambiente',
    descricaoFonte: 'Greve no entorno da sede ou filial',
    ameaca: 'Ativistas podem interditar ruas impedindo funcionarios de chegar à empresa',
    descricaoRisco: 'Uma greve impossibilitando funcionarios de chegar a empresa causando parada nos processos por falta de equipe',
    estrategico: 'SIM',
    tipoRisco: 'Risco Humano (Pessoas e Cultura Organizacional)',
    probabilidade: 1,
    impacto: 4,
    riscoInerente: 4,
    consequencia: 'Impacto nas operações',
    gravidade: 3,
    urgencia: 2,
    tendencia: 2,
    gutScore: 12,
    tratamento: 'Mitigar',
    controles: 'Acompanhamento de eventos externos; Comunicação interna; Uso de VPN para trabalho remoto',
    responsavel: 'Diretoria de Riscos, Compliance',
    prazo: '30 dias',
    kri: 'KRI1 -Relação Sindical;\nKRI2- Dependencia Operacional',
    acaoKri: 'Sala de crise para acompanhamento; Liberação para trabalho remoto; realocação de equipes; redistribuição de tarefas',
    quemMede: 'Diretoria de Riscos e Crises; RH e Juridico',
    quandoMede: 'Diariamente',
    reducaoPretendida: 1,
    riscoResidual: 1,
    eficaciaTratamento: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export interface EvolutionChange {
  riskId: string;
  type: 'new' | 'modified' | 'unchanged';
  changes: string[];
}

export const EVOLUTION_SUMMARY: EvolutionChange[] = [
  { riskId: 'R001', type: 'unchanged', changes: [] },
  { riskId: 'R002', type: 'unchanged', changes: [] },
  { riskId: 'R003', type: 'modified', changes: ['Descricao da Fonte'] },
  { riskId: 'R004', type: 'modified', changes: ['Descricao da Fonte'] },
  { riskId: 'R005', type: 'modified', changes: ['Descricao', 'Ameaca', 'Descricao da Fonte'] },
  { riskId: 'R006', type: 'modified', changes: ['Descricao', 'Ameaca', 'Descricao da Fonte'] },
  { riskId: 'R007', type: 'modified', changes: ['Descricao', 'Ameaca', 'Fonte de Risco'] },
  { riskId: 'R008', type: 'modified', changes: ['Descricao', 'Ameaca', 'Descricao da Fonte'] },
  { riskId: 'R009', type: 'unchanged', changes: [] },
  { riskId: 'R010', type: 'modified', changes: ['Descricao', 'Ameaca', 'Descricao da Fonte', 'Controles', 'KRI'] },
  { riskId: 'R011', type: 'modified', changes: ['Descricao', 'Ameaca', 'Descricao da Fonte'] },
  { riskId: 'R012', type: 'unchanged', changes: [] },
  { riskId: 'R013', type: 'unchanged', changes: [] },
  { riskId: 'R014', type: 'modified', changes: ['KRI'] },
  { riskId: 'R016', type: 'unchanged', changes: [] },
  { riskId: 'R017', type: 'unchanged', changes: [] },
  { riskId: 'R018', type: 'unchanged', changes: [] },
  { riskId: 'R019', type: 'unchanged', changes: [] },
  { riskId: 'R021', type: 'new', changes: ['Novo risco adicionado na Aula 4'] },
  { riskId: 'R022', type: 'new', changes: ['Novo risco adicionado na Aula 4'] },
  { riskId: 'R023', type: 'new', changes: ['Novo risco adicionado na Aula 4'] },
];

