// Dados de impacto financeiro por risco
// Premissas: DAMACORP - Faturamento R$ 350M/ano, e-commerce B2C/B2B, 24/7
// Alta demanda = Black Friday, Natal, datas sazonais (~3x faturamento normal)
// Baixa demanda = meses normais (~72% do faturamento médio)
// Média ponderada: 30% alta (3 meses) + 70% baixa (9 meses)
import { FinancialImpact } from './models';

export const FINANCIAL_DATA: Record<string, FinancialImpact> = {
  'R003': {
    perdaAltaDemanda: 14500000,
    perdaBaixaDemanda: 4800000,
    perdaMediaEsperada: 7710000,
    investimentoPreventivo: 850000,
    descricaoInvestimento: 'Plano de Continuidade de Negócios (BCP) com RTO/RPO definidos; sistema SAP redundante em hot-standby; procedimentos de contingência manual testados trimestralmente; acordo de SLA com fornecedor SAP com penalidades',
    perdaEvitada: 6860000,
    roiPrevencao: 807.1,
    racional: 'Parada no faturamento por 5 dias (25-30 do mês). Alta demanda: R$ 2.9M/dia x 5 dias = R$ 14.5M. Baixa: R$ 960K/dia x 5 = R$ 4.8M. Inclui multas contratuais e retrabalho.',
    categoria: 'Receita',
  },
  'R004': {
    perdaAltaDemanda: 8200000,
    perdaBaixaDemanda: 3100000,
    perdaMediaEsperada: 4630000,
    investimentoPreventivo: 1200000,
    descricaoInvestimento: 'Reforço de segurança patrimonial nos 3 CDs (vigilância armada 24h, CFTV com monitoramento remoto, controle de acesso biométrico, cercas elétricas, iluminação perimetral); seguro patrimonial amplo',
    perdaEvitada: 3430000,
    roiPrevencao: 285.8,
    racional: 'Assalto em CD: perda de mercadorias (R$ 2-5M), parada operacional de 3-7 dias, custos com seguros e indenizações. Alta demanda: estoque 3x maior = perda proporcional.',
    categoria: 'Operacional',
  },
  'R005': {
    perdaAltaDemanda: 35000000,
    perdaBaixaDemanda: 12000000,
    perdaMediaEsperada: 18900000,
    investimentoPreventivo: 2800000,
    descricaoInvestimento: 'SOC (Security Operations Center) 24/7; WAF e IDS/IPS; criptografia de dados em repouso e trânsito; programa de bug bounty; seguro cibernético; treinamento de conscientização para 100% dos colaboradores; testes de penetração semestrais',
    perdaEvitada: 16100000,
    roiPrevencao: 575.0,
    racional: 'Vazamento de dados: multa LGPD até 2% do faturamento (R$ 7M), perda de clientes (15-20% da base), custos de remediação, processos judiciais. Alta demanda: exposição de dados 3x maior, impacto reputacional amplificado.',
    categoria: 'Receita',
  },
  'R006': {
    perdaAltaDemanda: 18000000,
    perdaBaixaDemanda: 5500000,
    perdaMediaEsperada: 9250000,
    investimentoPreventivo: 1500000,
    descricaoInvestimento: 'Sistema de precificação dinâmica com validação automática; monitoramento de preços da concorrência em tempo real; SLA com transportadoras com penalidades; rastreamento de entregas em tempo real; equipe dedicada de customer success',
    perdaEvitada: 7750000,
    roiPrevencao: 516.7,
    racional: 'Erro de precificação em alta demanda pode gerar vendas com prejuízo (margem negativa) ou perda de vendas. Falha na entrega: 30% dos pedidos em datas críticas = R$ 18M em chargebacks e devoluções.',
    categoria: 'Receita',
  },
  'R007': {
    perdaAltaDemanda: 43500000,
    perdaBaixaDemanda: 10400000,
    perdaMediaEsperada: 20330000,
    investimentoPreventivo: 3500000,
    descricaoInvestimento: 'Infraestrutura multi-cloud (AWS + Azure) com failover automático; CDN distribuída; monitoramento de uptime 99.99%; disaster recovery com RTO < 1h; testes de failover mensais; contrato com SLA 99.95% e penalidades',
    perdaEvitada: 16830000,
    roiPrevencao: 480.9,
    racional: 'Indisponibilidade total do e-commerce por 15 dias. Alta demanda: R$ 2.9M/dia x 15 = R$ 43.5M em vendas perdidas. Baixa: R$ 694K/dia x 15 = R$ 10.4M. Inclui danos reputacionais e perda de clientes.',
    categoria: 'Receita',
  },
  'R008': {
    perdaAltaDemanda: 9500000,
    perdaBaixaDemanda: 3200000,
    perdaMediaEsperada: 5090000,
    investimentoPreventivo: 750000,
    descricaoInvestimento: 'Plano de contingência logística com rotas alternativas; parcerias com múltiplas transportadoras; seguro de carga; estoque de segurança distribuído nos 3 CDs; comunicação proativa com clientes em caso de atrasos',
    perdaEvitada: 4340000,
    roiPrevencao: 578.7,
    racional: 'Enchente bloqueando logística por 7-10 dias. Alta demanda: R$ 950K/dia em entregas atrasadas x 10 dias. Baixa: R$ 320K/dia x 10. Inclui custos de frete emergencial e devoluções.',
    categoria: 'Operacional',
  },
  'R009': {
    perdaAltaDemanda: 22000000,
    perdaBaixaDemanda: 8500000,
    perdaMediaEsperada: 12550000,
    investimentoPreventivo: 1800000,
    descricaoInvestimento: 'Governança corporativa robusta com conselho consultivo; acordo de sócios atualizado; planejamento sucessório; reserva financeira de contingência (6 meses de opex); auditoria independente anual; comunicação institucional profissional',
    perdaEvitada: 10750000,
    roiPrevencao: 597.2,
    racional: 'Crise institucional afetando confiança de investidores e parceiros. Perda de 5-8% do faturamento anual por queda de confiança. Alta demanda: impacto amplificado pela exposição midiática sazonal.',
    categoria: 'Reputacional',
  },
  'R010': {
    perdaAltaDemanda: 52500000,
    perdaBaixaDemanda: 17500000,
    perdaMediaEsperada: 28000000,
    investimentoPreventivo: 4200000,
    descricaoInvestimento: 'Zero Trust Architecture; segregação de funções (SoD); DLP (Data Loss Prevention); monitoramento de comportamento anômalo (UEBA); background check rigoroso; programa de ética e compliance; canal de denúncias anônimo; revisão trimestral de acessos',
    perdaEvitada: 23800000,
    roiPrevencao: 566.7,
    racional: 'Sabotagem interna com acesso privilegiado: vazamento massivo + parada operacional. Perda de até 15% do faturamento anual. Alta demanda: dados de 3x mais transações expostos, multas LGPD + processos coletivos.',
    categoria: 'Receita',
  },
  'R011': {
    perdaAltaDemanda: 7000000,
    perdaBaixaDemanda: 3500000,
    perdaMediaEsperada: 4550000,
    investimentoPreventivo: 600000,
    descricaoInvestimento: 'Due diligence rigorosa de fornecedores; sistema de homologação com scoring; auditoria periódica de fornecedores críticos; segregação de aprovações de pagamento; sistema antifraude em contas a pagar',
    perdaEvitada: 3950000,
    roiPrevencao: 658.3,
    racional: 'Fraude via fornecedores fictícios: desvio médio de 1-2% do volume de compras. Compras anuais ~R$ 175M (50% do faturamento). Alta demanda: volume de compras 3x maior, maior pressão por agilidade = menor controle.',
    categoria: 'Operacional',
  },
  'R012': {
    perdaAltaDemanda: 5000000,
    perdaBaixaDemanda: 3000000,
    perdaMediaEsperada: 3600000,
    investimentoPreventivo: 800000,
    descricaoInvestimento: 'Estudo de viabilidade detalhado antes de diversificação; consultoria especializada; projeto piloto com investimento limitado; métricas de go/no-go; reserva de capital para novos negócios separada do operacional',
    perdaEvitada: 2800000,
    roiPrevencao: 350.0,
    racional: 'Diversificação sem expertise: investimento perdido de R$ 3-5M em novos segmentos. Impacto similar em alta e baixa demanda pois é investimento estratégico, não operacional.',
    categoria: 'Operacional',
  },
  'R013': {
    perdaAltaDemanda: 28000000,
    perdaBaixaDemanda: 8000000,
    perdaMediaEsperada: 14000000,
    investimentoPreventivo: 2200000,
    descricaoInvestimento: 'Plano de marketing digital agressivo com ROI mensurado; programa de fidelidade; expansão de marketplace; otimização de conversão (CRO); investimento em mídia paga segmentada; parcerias estratégicas com influenciadores',
    perdaEvitada: 11800000,
    roiPrevencao: 536.4,
    racional: 'Não atingir meta de +8% receita = perda de R$ 28M em alta demanda (onde se concentra 40% do faturamento). Baixa demanda: R$ 8M de receita não capturada. Meta: R$ 378M vs R$ 350M.',
    categoria: 'Receita',
  },
  'R014': {
    perdaAltaDemanda: 15000000,
    perdaBaixaDemanda: 8000000,
    perdaMediaEsperada: 10100000,
    investimentoPreventivo: 1100000,
    descricaoInvestimento: 'Repositório corporativo seguro (GitLab/GitHub Enterprise); bloqueio de dispositivos USB; DLP para código-fonte; política de BYOD restritiva; monitoramento de uploads para nuvem pessoal; NDA reforçado com penalidades; revisão de código obrigatória',
    perdaEvitada: 9000000,
    roiPrevencao: 818.2,
    racional: 'Vazamento de código-fonte: perda de vantagem competitiva, exploração de vulnerabilidades. Custo de remediação + perda de mercado. Alta demanda: concorrentes podem explorar vulnerabilidades em período crítico.',
    categoria: 'Operacional',
  },
  'R015': {
    perdaAltaDemanda: 21000000,
    perdaBaixaDemanda: 4200000,
    perdaMediaEsperada: 9240000,
    investimentoPreventivo: 1600000,
    descricaoInvestimento: 'Sistema de gestão de estoque com IA preditiva; múltiplos fornecedores por categoria; estoque de segurança dinâmico (maior em pré-sazonalidade); contratos de fornecimento com cláusula de prioridade; cross-docking otimizado',
    perdaEvitada: 7640000,
    roiPrevencao: 477.5,
    racional: 'Ruptura de estoque: perda direta de vendas. Alta demanda: R$ 2.9M/dia x 7 dias de ruptura parcial (25% do catálogo) = R$ 21M. Baixa: R$ 694K/dia x 7 x 25% catálogo afetado.',
    categoria: 'Receita',
  },
  'R016': {
    perdaAltaDemanda: 12000000,
    perdaBaixaDemanda: 7000000,
    perdaMediaEsperada: 8500000,
    investimentoPreventivo: 1800000,
    descricaoInvestimento: 'Departamento de compliance dedicado; sistema de gestão de conformidade (GRC); monitoramento regulatório automatizado; treinamento obrigatório em LGPD, CDC e Marco Civil; auditorias de conformidade semestrais; assessoria jurídica especializada',
    perdaEvitada: 6700000,
    roiPrevencao: 372.2,
    racional: 'Multas regulatórias: LGPD até 2% (R$ 7M), PROCON, ANATEL. Alta demanda: maior volume de transações = maior exposição a reclamações e fiscalizações. Inclui custos de adequação emergencial.',
    categoria: 'Regulatório',
  },
  'R017': {
    perdaAltaDemanda: 26000000,
    perdaBaixaDemanda: 9100000,
    perdaMediaEsperada: 14170000,
    investimentoPreventivo: 2500000,
    descricaoInvestimento: 'Estratégia omnichannel; expansão geográfica com análise de mercado; aquisição de concorrentes menores; investimento em tecnologia de personalização; programa de indicação de clientes; presença em novos marketplaces',
    perdaEvitada: 11670000,
    roiPrevencao: 466.8,
    racional: 'Não atingir meta de +26% market share: receita não capturada de R$ 91M (26% de R$ 350M). Considerando probabilidade parcial: alta demanda R$ 26M, baixa R$ 9.1M de oportunidade perdida.',
    categoria: 'Receita',
  },
  'R018': {
    perdaAltaDemanda: 11000000,
    perdaBaixaDemanda: 5500000,
    perdaMediaEsperada: 7150000,
    investimentoPreventivo: 1200000,
    descricaoInvestimento: 'Acordo de sócios revisado com cláusulas de resolução de conflitos; conselho consultivo independente; governança com comitês (auditoria, riscos, remuneração); seguro D&O; mediação profissional preventiva',
    perdaEvitada: 5950000,
    roiPrevencao: 495.8,
    racional: 'Conflitos societários: paralisia decisória, perda de oportunidades, saída de executivos-chave. Impacto de 3-5% do faturamento. Alta demanda: decisões críticas de compra e pricing atrasadas.',
    categoria: 'Reputacional',
  },
  'R019': {
    perdaAltaDemanda: 6500000,
    perdaBaixaDemanda: 4200000,
    perdaMediaEsperada: 4890000,
    investimentoPreventivo: 1500000,
    descricaoInvestimento: 'Programa de retenção de talentos (bônus, stock options, plano de carreira); pesquisa de clima organizacional semestral; benchmark salarial anual; programa de desenvolvimento de lideranças; onboarding estruturado; benefícios flexíveis',
    perdaEvitada: 3390000,
    roiPrevencao: 226.0,
    racional: 'Turnover elevado: custo de reposição = 1.5x salário anual por posição. Com 1.000 colaboradores e turnover de 15%: 150 reposições x R$ 35K médio = R$ 5.25M. Alta demanda: impacto operacional amplificado.',
    categoria: 'Operacional',
  },
  'R020': {
    perdaAltaDemanda: 14000000,
    perdaBaixaDemanda: 7000000,
    perdaMediaEsperada: 9100000,
    investimentoPreventivo: 1600000,
    descricaoInvestimento: 'DPO (Data Protection Officer) dedicado; programa de adequação LGPD completo; Privacy by Design em todos os sistemas; DPIA (Data Protection Impact Assessment) para novos projetos; resposta a incidentes de dados com SLA < 72h',
    perdaEvitada: 7500000,
    roiPrevencao: 468.8,
    racional: 'Multa ANPD: até 2% do faturamento (R$ 7M) + sanções (suspensão de tratamento de dados). Alta demanda: maior volume de dados coletados = maior exposição. Inclui custos de adequação e danos reputacionais.',
    categoria: 'Regulatório',
  },
  'R021': {
    perdaAltaDemanda: 3500000,
    perdaBaixaDemanda: 2000000,
    perdaMediaEsperada: 2450000,
    investimentoPreventivo: 500000,
    descricaoInvestimento: 'Sistema de detecção e supressão de incêndio nos CDs; brigada de incêndio treinada; seguro patrimonial com cobertura ampla; backup de dados off-site; plano de evacuação testado; manutenção preventiva de instalações elétricas',
    perdaEvitada: 1950000,
    roiPrevencao: 390.0,
    racional: 'Incêndio em DC/CD: perda de equipamentos e estoque parcial. Probabilidade baixa (1/5) mas impacto significativo. Alta demanda: estoque 3x maior em risco. Seguro cobre parte mas não o downtime.',
    categoria: 'Segurança',
  },
  'R022': {
    perdaAltaDemanda: 25000000,
    perdaBaixaDemanda: 8000000,
    perdaMediaEsperada: 13100000,
    investimentoPreventivo: 1800000,
    descricaoInvestimento: 'Princípio do menor privilégio (PoLP); revisão de acessos mensal; monitoramento de atividades privilegiadas (PAM); classificação de informação; watermarking em documentos confidenciais; NDA com penalidades severas; investigação forense em caso de vazamento',
    perdaEvitada: 11300000,
    roiPrevencao: 627.8,
    racional: 'Vazamento de campanhas e estratégias por funcionário: concorrentes antecipam promoções, perda de vantagem competitiva. Alta demanda: campanhas de Black Friday/Natal valem 30% do faturamento anual.',
    categoria: 'Receita',
  },
  'R023': {
    perdaAltaDemanda: 4500000,
    perdaBaixaDemanda: 1500000,
    perdaMediaEsperada: 2400000,
    investimentoPreventivo: 400000,
    descricaoInvestimento: 'Plano de contingência para greves; equipe mínima essencial definida; trabalho remoto habilitado para funções administrativas; relacionamento proativo com sindicatos; programa de benefícios competitivo; comunicação transparente com colaboradores',
    perdaEvitada: 2000000,
    roiPrevencao: 500.0,
    racional: 'Greve de 5-7 dias: parada parcial dos CDs. Alta demanda: R$ 2.9M/dia x 5 dias x 30% impacto = R$ 4.5M. Baixa: R$ 694K/dia x 5 x 40% = R$ 1.5M. Probabilidade baixa (1/5).',
    categoria: 'Operacional',
  },
  'R024': {
    perdaAltaDemanda: 16000000,
    perdaBaixaDemanda: 6500000,
    perdaMediaEsperada: 9350000,
    investimentoPreventivo: 2000000,
    descricaoInvestimento: 'Contratação de CISO (Chief Information Security Officer); equipe de segurança da informação (mínimo 3 profissionais); SIEM (Security Information and Event Management); programa de awareness; certificação ISO 27001; pentest trimestral',
    perdaEvitada: 7350000,
    roiPrevencao: 367.5,
    racional: 'Sem profissional de SI: vulnerabilidades não detectadas, resposta lenta a incidentes. Custo médio de breach no Brasil: R$ 6.5M. Alta demanda: superfície de ataque 3x maior, dados mais valiosos.',
    categoria: 'Segurança',
  },
  'R025': {
    perdaAltaDemanda: 9000000,
    perdaBaixaDemanda: 4500000,
    perdaMediaEsperada: 5850000,
    investimentoPreventivo: 800000,
    descricaoInvestimento: 'Contrato com agência incluindo cláusulas LGPD; acesso restrito via API (sem acesso direto ao banco); anonimização de dados para campanhas; auditoria de acesso trimestral; DPA (Data Processing Agreement) formal; monitoramento de exportação de dados',
    perdaEvitada: 5050000,
    roiPrevencao: 631.2,
    racional: 'Agência com acesso a dados de clientes: vazamento por terceiro. Multa LGPD + processos + perda de clientes. Alta demanda: base de dados maior (campanhas sazonais captam mais leads).',
    categoria: 'Regulatório',
  },
  'R026': {
    perdaAltaDemanda: 12000000,
    perdaBaixaDemanda: 2800000,
    perdaMediaEsperada: 5560000,
    investimentoPreventivo: 900000,
    descricaoInvestimento: 'Sistema de gestão de estoque com previsão de demanda por IA; safety stock dinâmico; múltiplos fornecedores por SKU; VMI (Vendor Managed Inventory) com fornecedores-chave; cross-docking otimizado; alertas automáticos de ruptura',
    perdaEvitada: 4660000,
    roiPrevencao: 517.8,
    racional: 'Estoque zero com ruptura: perda de vendas direta. Alta demanda: R$ 2.9M/dia x 4 dias de ruptura = R$ 12M. Baixa: R$ 694K/dia x 4 = R$ 2.8M. Inclui perda de clientes para concorrentes.',
    categoria: 'Receita',
  },
  'R027': {
    perdaAltaDemanda: 10500000,
    perdaBaixaDemanda: 3500000,
    perdaMediaEsperada: 5600000,
    investimentoPreventivo: 1200000,
    descricaoInvestimento: 'Sistema antifraude com machine learning; 3D Secure 2.0 em pagamentos; verificação de identidade em compras de alto valor; equipe de análise de fraude; chargeback management; parceria com bandeiras de cartão para alertas',
    perdaEvitada: 4400000,
    roiPrevencao: 366.7,
    racional: 'Fraude em e-commerce: taxa média de 1.5-3% do GMV. Faturamento e-commerce ~R$ 350M. Alta demanda: volume 3x maior, fraudadores mais ativos. Chargebacks + mercadorias perdidas + custos operacionais.',
    categoria: 'Receita',
  },
  'R001': {
    perdaAltaDemanda: 25000000,
    perdaBaixaDemanda: 8000000,
    perdaMediaEsperada: 13100000,
    investimentoPreventivo: 3500000,
    descricaoInvestimento: 'Programa de fidelidade com cashback; parcerias exclusivas com fabricantes; investimento em marca própria (private label); análise competitiva mensal; fortalecimento de branding e UX do site próprio; equipe de inteligência de mercado',
    perdaEvitada: 9600000,
    roiPrevencao: 274.3,
    racional: 'Perda de market share de 5-7% ao ano para marketplaces com logística própria. Faturamento R$ 350M: 7% = R$ 24.5M em alta demanda. Baixa: 2.3% = R$ 8M. Inclui compressão de margens para competir em preço.',
    categoria: 'Receita',
  },
  'R002': {
    perdaAltaDemanda: 70000000,
    perdaBaixaDemanda: 25000000,
    perdaMediaEsperada: 38500000,
    investimentoPreventivo: 5000000,
    descricaoInvestimento: 'Reserva financeira de contingência (3 meses de opex); diversificação de categorias (essenciais vs. discricionários); flexibilização de contratos com fornecedores; monitoramento macroeconômico; hedge cambial; plano de redução de custos escalonado',
    perdaEvitada: 33500000,
    roiPrevencao: 670.0,
    racional: 'Recessão pode reduzir faturamento em 20-30%. Faturamento R$ 350M: 20% = R$ 70M em alta demanda. Baixa: ~7% = R$ 25M. Inclui inadimplência B2B, demissões e custos de reestruturação.',
    categoria: 'Receita',
  },
  'R028': {
    perdaAltaDemanda: 8000000,
    perdaBaixaDemanda: 3000000,
    perdaMediaEsperada: 4500000,
    investimentoPreventivo: 900000,
    descricaoInvestimento: 'Sistema de previsão de demanda com IA/ML; política de giro máximo por categoria; acordos de devolução com fabricantes; outlet digital para liquidação rápida; dashboard de aging de estoque',
    perdaEvitada: 3600000,
    roiPrevencao: 400.0,
    racional: 'Estoque obsoleto: liquidação com 30-70% de desconto. Estoque médio R$ 20M, 10% obsoleto = R$ 2M de perda direta + custos de armazenagem. Alta demanda: compras 3x maiores amplificam o risco.',
    categoria: 'Operacional',
  },
  'R029': {
    perdaAltaDemanda: 15000000,
    perdaBaixaDemanda: 6000000,
    perdaMediaEsperada: 8700000,
    investimentoPreventivo: 1800000,
    descricaoInvestimento: 'Programa de change management; treinamentos obrigatórios em gestão de riscos; metas de adoção de controles nos KPIs; pesquisa de clima; reconhecimento de boas práticas; coaching executivo',
    perdaEvitada: 6900000,
    roiPrevencao: 383.3,
    racional: 'Fracasso de projetos de transformação: 40% dos investimentos desperdiçados (R$ 6M/ano). Manutenção de vulnerabilidades: custo de incidentes evitáveis R$ 9M em alta demanda. Turnover de talentos: R$ 150K/posição.',
    categoria: 'Operacional',
  },
  'R030': {
    perdaAltaDemanda: 20000000,
    perdaBaixaDemanda: 4000000,
    perdaMediaEsperada: 8800000,
    investimentoPreventivo: 1500000,
    descricaoInvestimento: 'Segundo gateway de pagamento com failover automático; testes de carga sazonais; monitoramento de taxa de aprovação em tempo real; SLA com penalidades; PIX como alternativa; checkout de contingência',
    perdaEvitada: 7300000,
    roiPrevencao: 486.7,
    racional: 'Falha de gateway em Black Friday: R$ 2.9M/dia x 7 dias de pico = R$ 20M. Baixa demanda: R$ 694K/dia x 6 dias = R$ 4M. Inclui abandono de carrinho e migração de clientes.',
    categoria: 'Receita',
  },
  'R031': {
    perdaAltaDemanda: 30000000,
    perdaBaixaDemanda: 10000000,
    perdaMediaEsperada: 16000000,
    investimentoPreventivo: 2000000,
    descricaoInvestimento: 'Exit plan documentado; backup em provedor secundário; arquitetura com containers (Docker/K8s); cláusula de assistência à migração; avaliação anual de alternativas; SLA com penalidades',
    perdaEvitada: 14000000,
    roiPrevencao: 700.0,
    racional: 'Paralisação total por falha do provedor: R$ 2.9M/dia x 10 dias = R$ 29M em alta demanda. Custos de migração emergencial: R$ 5M. Baixa: R$ 694K/dia x 14 dias = R$ 10M.',
    categoria: 'Operacional',
  },
  'R032': {
    perdaAltaDemanda: 18000000,
    perdaBaixaDemanda: 12000000,
    perdaMediaEsperada: 13800000,
    investimentoPreventivo: 2500000,
    descricaoInvestimento: 'Consultoria tributária especializada; simulação de cenários de impacto; atualização de sistemas fiscais (ERP/SAP); revisão de estrutura logística; lobby setorial via ABComm; reserva para custos de transição',
    perdaEvitada: 11300000,
    roiPrevencao: 452.0,
    racional: 'Aumento de carga tributária de 3-5pp sobre faturamento de R$ 350M = R$ 10.5-17.5M/ano. Autuações por erro na transição: até R$ 3M. Custos de adaptação de sistemas: R$ 1.5M.',
    categoria: 'Regulatório',
  },
  'R033': {
    perdaAltaDemanda: 6000000,
    perdaBaixaDemanda: 3500000,
    perdaMediaEsperada: 4250000,
    investimentoPreventivo: 1200000,
    descricaoInvestimento: 'Programa de saúde mental e bem-estar; dimensionamento adequado de equipes 24/7; política de horas extras com limites; pesquisa de clima trimestral; plano de carreira; flexibilidade de trabalho remoto',
    perdaEvitada: 3050000,
    roiPrevencao: 254.2,
    racional: 'Custo de turnover: R$ 150K/posição x 20 saídas/ano = R$ 3M. Afastamentos por burnout: R$ 50K/colaborador x 30 = R$ 1.5M. Erros operacionais por fadiga: R$ 1.5M em alta demanda.',
    categoria: 'Operacional',
  },
  'R034': {
    perdaAltaDemanda: 16000000,
    perdaBaixaDemanda: 5000000,
    perdaMediaEsperada: 8300000,
    investimentoPreventivo: 1800000,
    descricaoInvestimento: 'Contrato com 3+ transportadoras por região; SLA com penalidades; monitoramento OTIF em tempo real; seguro de carga; transportadoras reserva; scorecard trimestral de desempenho',
    perdaEvitada: 6500000,
    roiPrevencao: 361.1,
    racional: 'Falha logística last-mile: 15% dos pedidos atrasados em alta demanda = R$ 16M (chargebacks + devoluções + frete emergencial). Baixa: 8% = R$ 5M. Inclui dano reputacional e perda de recorrência.',
    categoria: 'Operacional',
  },
  'R035': {
    perdaAltaDemanda: 12000000,
    perdaBaixaDemanda: 6000000,
    perdaMediaEsperada: 7800000,
    investimentoPreventivo: 800000,
    descricaoInvestimento: 'Sistema de análise de crédito automatizado (score + Serasa/SPC); limites de crédito por cliente; seguro de crédito para operações acima de R$ 50K; cobrança preventiva automatizada; cláusulas de garantia',
    perdaEvitada: 7000000,
    roiPrevencao: 875.0,
    racional: 'Inadimplência B2B de 8-10% sobre carteira de R$ 120M = R$ 9.6-12M. Alta demanda: vendas maiores amplificam exposição. Custos de cobrança judicial: R$ 500K/ano. PDD: 3% do faturamento B2B.',
    categoria: 'Receita',
  },
  'R036': {
    perdaAltaDemanda: 14000000,
    perdaBaixaDemanda: 4500000,
    perdaMediaEsperada: 7350000,
    investimentoPreventivo: 1000000,
    descricaoInvestimento: 'Mapeamento de fornecedores alternativos; política de dual sourcing; avaliação financeira anual de fornecedores; estoque de segurança para itens de fornecedor único; cláusulas de contingência',
    perdaEvitada: 6350000,
    roiPrevencao: 635.0,
    racional: 'Ruptura de fornecedor-chave: perda de vendas de R$ 2M/dia x 7 dias = R$ 14M em alta demanda. Baixa: R$ 640K/dia x 7 = R$ 4.5M. Inclui custos de compra emergencial e perda de clientes.',
    categoria: 'Receita',
  },
  'R037': {
    perdaAltaDemanda: 10000000,
    perdaBaixaDemanda: 5000000,
    perdaMediaEsperada: 6500000,
    investimentoPreventivo: 1200000,
    descricaoInvestimento: 'Hedge cambial para compras programadas; diversificação de fornecedores nacionais; cláusulas de reajuste cambial; monitoramento diário de câmbio; reserva cambial para 60 dias; preços dinâmicos com ajuste cambial',
    perdaEvitada: 5300000,
    roiPrevencao: 441.7,
    racional: 'Desvalorização de 15-20% do real: custo de importados sobe R$ 10M em alta demanda (estoque 3x). Baixa: R$ 5M. Compressão de margens de 3-5pp. Inclui custos de hedge e repasse de preços.',
    categoria: 'Receita',
  },
};

// === RESUMO CONSOLIDADO (37 RISCOS) ===
// Perda média esperada total: R$ 377,570,000
// Investimento preventivo total: R$ 62,300,000
// Perda evitada total: R$ 315,270,000
// ROI da prevenção: 506.1%
